childBlocks: null
conditions: null
description: ''
enabled: true
field: f69cfc32-4011-4eea-a32a-f5ae9fd5b24e # Page Builder: General
fieldLayouts:
  3106edaf-a916-4700-8455-3cd8783031a8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a8366a49-97a6-4a33-a567-a948f6a481ac # Section ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7aa3fd83-ba77-4388-aa50-745bc8a71d74
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 17fcc0b6-4e93-425f-9380-11c07300553d # Buttons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2cc6681b-886c-481f-9c0e-b2a98f8b1ba2
            userCondition: null
            warning: null
            width: 100
        name: Buttons
        uid: f12a755a-65b6-41d9-a90e-6a7b359b57db
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: dfbc0047-f74f-4940-baf3-7f9402fc918e # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e3f9921d-383a-40a0-b809-6fa7b480b649
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 28a04878-3d6a-4889-ad36-87cce2dd449e # Padding: Top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 361c09b7-ff58-4f3c-b91d-ca2333d8cf05
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 040d7db9-375b-4b41-989d-2e38c47b90f6 # Padding: Bottom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d3e18285-b20f-4069-9bd9-662eb197067a
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 12a86971-9af3-496d-9a73-1f277506afaa # Padding: Sides
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 43729187-42e9-4fd8-9dd4-705f29d55e7f
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: fb633af9-99e4-499c-b90f-60a8039f3046 # Text Alignment
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a97dbd5-0270-420e-bfb7-e1c6d9397bb3
            userCondition: null
            warning: null
            width: 25
        name: 'Section Settings'
        uid: 35ad1403-35b7-4e02-80db-e6cc494f0a8e
        userCondition: null
group: null
groupChildBlockTypes: true
handle: buttonBlock
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Button Block'
topLevel: true
