childBlocks: null
conditions: null
description: ''
enabled: true
field: 23354ff5-9e58-4f25-a8b1-77c6f7b7b7d8 # Page Header
fieldLayouts:
  2a69acc2-4db0-4507-8f70-ad4878053401:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6ab970bd-1621-4c3f-8eeb-6887ac8cbb2c # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f5ff0fa-edf9-4100-945b-977e994a3f29
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d4a66aad-fd77-4abe-97e2-a01cabc77bac # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a9cc20d8-a30d-4e28-8c09-a764f13ea0e0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 17fcc0b6-4e93-425f-9380-11c07300553d # Buttons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2fa6d435-4c80-448a-b378-f9d03320986a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9d31fd99-c9e0-403e-9278-ff2043e607a7
        userCondition: null
group: null
groupChildBlockTypes: true
handle: centeredText
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Centered Text'
topLevel: true
