childBlocks:
  - columnText
  - columnImage
conditions: null
description: ''
enabled: true
field: 0914ee96-13fc-4737-ae93-8ab00d611b35 # Page Builder: Blog
fieldLayouts:
  14d23e49-89c5-4ff6-9657-6f153fe916de:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: aa3d7fc1-1a22-4fff-8fe2-28dd1ab8388e # Pre-heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c57f977-77cd-4c43-8ae6-7366e047dfdf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 31f2b911-731f-42b5-84c6-4b2777260f2f # Section Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d79b0d48-1e90-4cd8-b187-23455deb88f2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e737770c-c6ad-40e0-8b58-fbea5931980f
        userCondition: null
group: null
groupChildBlockTypes: true
handle: columns
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Columns
sortOrder: 4
topLevel: true
