childBlocks: null
conditions: null
description: ''
enabled: true
field: 2cc57a96-1052-495e-a015-6a4984a4fa2d # Page Builder: Login
fieldLayouts:
  e2db7ba5-5ddd-4213-8c5b-bbe294d95c57:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d4a66aad-fd77-4abe-97e2-a01cabc77bac # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3c1d0de7-d26b-4f94-841d-44dbd7b8bdaf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8d53efd7-98eb-40ec-a000-4b904766072d # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 590381f3-269a-43b8-95d5-7f35e6e7ea6a
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 0014573b-36a9-48c6-b523-64fbabf469f2 # Button Style
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: da6a8b69-3669-4e28-b55e-50972280a930
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 169d75cf-81e0-4017-a1fb-551c2ef8daea
        userCondition: null
group: null
groupChildBlockTypes: true
handle: contentBlock
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Content Block'
sortOrder: 1
topLevel: true
