childBlocks:
  - largeSmallSmall
  - smallSmallLarge
  - mediumMedium
conditions: null
description: ''
enabled: true
field: f69cfc32-4011-4eea-a32a-f5ae9fd5b24e # Page Builder: General
fieldLayouts:
  2203f2b6-2377-4e3d-9de5-be56f1d50a51:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a8366a49-97a6-4a33-a567-a948f6a481ac # Section ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a3fb2f70-0f48-405d-9c7a-2b87bfc3c514
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ef82b094-a52c-43b6-bc3d-e88bba161e1a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 28a04878-3d6a-4889-ad36-87cce2dd449e # Padding: Top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aed93528-b282-445d-ac82-54cd58362ddf
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 040d7db9-375b-4b41-989d-2e38c47b90f6 # Padding: Bottom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e484fdb3-d34a-43bc-a4da-f1aecf318c6a
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 12a86971-9af3-496d-9a73-1f277506afaa # Padding: Sides
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 33297d14-dea3-4d2e-8a7c-179ac897bdc5
            userCondition: null
            warning: null
            width: 25
        name: 'Section Settings'
        uid: 2dc118f6-7f49-43ba-8152-d1a5f8dcf03e
        userCondition: null
group: null
groupChildBlockTypes: true
handle: ctaTiles
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'CTA Tiles'
topLevel: true
