childBlocks: null
conditions: null
description: ''
enabled: true
field: aefea3fc-ff45-4615-b305-9079e2cc6c44 # Page Builder: Impact Report
fieldLayouts:
  35a05160-cfa6-49ab-a653-5928292513a4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d24ab695-25c2-4078-b7e4-b936aa667ac6 # Pre-Eyebrow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c5e47a34-a751-44d3-9278-25fa5036a8d9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e39974bd-ec97-4187-be91-a431e1a4fbd7 # Eyebrow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 06e14924-a40c-49ff-bf6c-83f50484a9b8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 31f2b911-731f-42b5-84c6-4b2777260f2f # Section Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4cb94af4-c7a2-4f96-a909-48ae615f62c9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d4a66aad-fd77-4abe-97e2-a01cabc77bac # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0fbab881-f960-48b9-b1c5-ee17659dc12e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6add601c-de5e-4e85-8618-137007c0f910 # Signatures
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fbe76b9d-3dc6-4e43-bda6-cc825e7ee4bb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8d53efd7-98eb-40ec-a000-4b904766072d # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2143d2cf-8370-46c6-8e73-6b51cd3637fc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0014573b-36a9-48c6-b523-64fbabf469f2 # Button Style
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cca92755-6700-4e64-b34d-ce6bfa6cc2a5
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 4927ec01-316b-456c-86ef-73bc62f72253
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 28a04878-3d6a-4889-ad36-87cce2dd449e # Padding: Top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eb131433-1a98-40eb-9be6-51565f01288b
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 040d7db9-375b-4b41-989d-2e38c47b90f6 # Padding: Bottom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e615d377-a0d6-491f-9777-2ad037dec425
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: fb633af9-99e4-499c-b90f-60a8039f3046 # Text Alignment
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12c76c00-ca72-4f90-9c45-11e4ec644668
            userCondition: null
            warning: null
            width: 25
        name: 'Section Settings'
        uid: 6fa7df07-978a-4849-9691-fee910609882
        userCondition: null
group: null
groupChildBlockTypes: true
handle: generalLargeText
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'General: Large Text'
topLevel: true
