childBlocks: null
conditions: null
description: ''
enabled: true
field: aefea3fc-ff45-4615-b305-9079e2cc6c44 # Page Builder: Impact Report
fieldLayouts:
  bf0b4273-c569-4622-9dd6-e2555d2ac4c1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 31f2b911-731f-42b5-84c6-4b2777260f2f # Section Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4cb94af4-c7a2-4f96-a909-48ae615f62c9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d4a66aad-fd77-4abe-97e2-a01cabc77bac # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0fbab881-f960-48b9-b1c5-ee17659dc12e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cec407c4-ded3-4457-9ffd-7caf96ab0281 # Caption
            instructions: null
            label: Signature
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d6d40391-3601-4543-9f1f-de4a5e3e464d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 17fcc0b6-4e93-425f-9380-11c07300553d # Buttons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b1a8a9ed-c820-491a-ac9f-5128b55317ee
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4927ec01-316b-456c-86ef-73bc62f72253
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 28a04878-3d6a-4889-ad36-87cce2dd449e # Padding: Top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eb131433-1a98-40eb-9be6-51565f01288b
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 040d7db9-375b-4b41-989d-2e38c47b90f6 # Padding: Bottom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e615d377-a0d6-491f-9777-2ad037dec425
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: fb633af9-99e4-499c-b90f-60a8039f3046 # Text Alignment
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12c76c00-ca72-4f90-9c45-11e4ec644668
            userCondition: null
            warning: null
            width: 25
        name: 'Section Settings'
        uid: 6fa7df07-978a-4849-9691-fee910609882
        userCondition: null
group: null
groupChildBlockTypes: true
handle: generalLargeText
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'General: Large Text'
topLevel: true
