childBlocks: null
conditions: null
description: ''
enabled: true
field: f69cfc32-4011-4eea-a32a-f5ae9fd5b24e # Page Builder: General
fieldLayouts:
  85bb59a8-ef0b-410c-9acd-d58dfa27fd2b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6ab970bd-1621-4c3f-8eeb-6887ac8cbb2c # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c37b55e-c7ce-49a1-998d-8c8fb32678b2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 17fcc0b6-4e93-425f-9380-11c07300553d # Buttons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ddcb523c-5e58-4270-bc2b-d813a9aae8a3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 90937a29-a65a-4dcb-806b-676ad9589320
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: dfbc0047-f74f-4940-baf3-7f9402fc918e # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 67268a93-cf23-4615-a273-71a3882c9758
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 55f89f73-30c8-4eeb-b491-a0da78da6657 # Text Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b3a8aa0e-3700-453e-8827-6ea80d559748
            userCondition: null
            warning: null
            width: 25
        name: 'Section Settings'
        uid: f9a240b1-aff0-4b34-a464-0a130377cd6a
        userCondition: null
group: null
groupChildBlockTypes: true
handle: headingButtonBar
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Heading+Button Bar'
topLevel: true
