childBlocks: null
conditions: null
description: ''
enabled: true
field: aefea3fc-ff45-4615-b305-9079e2cc6c44 # Page Builder: Impact Report
fieldLayouts:
  1ef619c5-431a-433e-80e1-5a568e77f616:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d24ab695-25c2-4078-b7e4-b936aa667ac6 # Pre-Eyebrow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f0182bba-91b7-49b7-bfaa-a2651b325a13
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e39974bd-ec97-4187-be91-a431e1a4fbd7 # Eyebrow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cfddf0ac-0a5f-4fe0-ae07-2e37d4c50066
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6ab970bd-1621-4c3f-8eeb-6887ac8cbb2c # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7c958974-7a39-4339-bb42-f9f4d49459cd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: aa3d7fc1-1a22-4fff-8fe2-28dd1ab8388e # Pre-heading
            instructions: null
            label: Subheading
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a3022adc-ed73-4f9a-9339-02b367a7e90f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d9994972-0f59-4134-b9b1-cd07d76bf05f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 28a04878-3d6a-4889-ad36-87cce2dd449e # Padding: Top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ee338594-9239-40db-9724-40bcb778ee85
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 040d7db9-375b-4b41-989d-2e38c47b90f6 # Padding: Bottom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b9033f5b-da75-48e9-a799-5443a8bfe62b
            userCondition: null
            warning: null
            width: 25
        name: 'Section Settings'
        uid: f32492c4-7f1d-4b0f-84cc-caa3839921f1
        userCondition: null
group: null
groupChildBlockTypes: true
handle: headingBlock
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Heading Block'
topLevel: true
