childBlocks: null
conditions: null
description: ''
enabled: true
field: 23354ff5-9e58-4f25-a8b1-77c6f7b7b7d8 # Page Header
fieldLayouts:
  474beb65-8f1b-4535-b469-44494fe5a143:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6ab970bd-1621-4c3f-8eeb-6887ac8cbb2c # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0869d716-a154-443b-bf96-e52fb5945fc6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cdb162a5-f0d2-429b-b5ac-588fc77a48da # Summary
            instructions: null
            label: 'Large Text'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c410e8b2-2f3c-4600-8a19-d730c9378ce4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ab08b54b-fc7b-493c-9f42-ef3e28b0cb81
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: dfbc0047-f74f-4940-baf3-7f9402fc918e # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e07f992-fc19-4eed-b169-24eb221d6717
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 55f89f73-30c8-4eeb-b491-a0da78da6657 # Text Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 782a8234-bde0-46b4-bff5-9b2e59eeb93f
            userCondition: null
            warning: null
            width: 25
        name: Settings
        uid: a1f96330-9b2c-4c21-af76-4fb4ca143b0c
        userCondition: null
group: null
groupChildBlockTypes: true
handle: largeText
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Large Text'
topLevel: true
