childBlocks: null
conditions: null
description: ''
enabled: true
field: f69cfc32-4011-4eea-a32a-f5ae9fd5b24e # Page Builder: General
fieldLayouts:
  6ecf6344-c7c0-4c02-899f-0d918a56a079:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'Insert one large and two small tiles. The large tile will be shown first.'
            type: craft\fieldlayoutelements\Tip
            uid: 869edfbe-c0f3-4dbe-b148-84d5af32fdf0
            userCondition: null
          -
            elementCondition: null
            fieldUid: 0990fff1-3f3d-49e5-a5b1-afdeb683d20e # CTA Tile: Large
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ce58557d-2726-4e0e-80ea-250f503eb4ad
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e11568a1-11e3-4147-ae18-1ff01fdcd4f7 # CTA Tile: Small
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa733b68-012b-422a-abf3-78bbfe944dc1
            userCondition: null
            warning: null
            width: 100
        name: Tiles
        uid: 89e492df-f324-4b9f-a3fb-08ffea0ff4c8
        userCondition: null
group: null
groupChildBlockTypes: true
handle: largeSmallSmall
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Large | Small | Small'
sortOrder: 7
topLevel: false
