childBlocks: null
conditions: null
description: ''
enabled: true
field: f69cfc32-4011-4eea-a32a-f5ae9fd5b24e # Page Builder: General
fieldLayouts:
  10625039-c3f8-439a-b1b7-2317288a5d4f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e11568a1-11e3-4147-ae18-1ff01fdcd4f7 # CTA Tile: Small
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f0bc8fd2-b193-4282-94f3-6750cb6e9865
            userCondition: null
            warning: null
            width: 100
        name: Tiles
        uid: 80e0ff76-6291-4bf2-8437-dc0be0b8fab7
        userCondition: null
group: null
groupChildBlockTypes: true
handle: mediumMedum
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Medium | Medium'
topLevel: false
