childBlocks: null
conditions: null
description: ''
enabled: true
field: aefea3fc-ff45-4615-b305-9079e2cc6c44 # Page Builder: Impact Report
fieldLayouts:
  b9356146-817c-40d3-bd7a-ff66c3d41802:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7f134341-6c01-4975-9ea9-60df3c3dd5f0 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 220cd65d-036c-4d26-bc39-ea114a47932d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: aa3d7fc1-1a22-4fff-8fe2-28dd1ab8388e # Pre-heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d0840dff-208b-4331-a8ed-169d224a859a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6ab970bd-1621-4c3f-8eeb-6887ac8cbb2c # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8c3d90e4-842e-4464-a169-55e6eb894d93
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9f83996e-3759-41eb-905a-a0101283ce27 # Subheading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1123f3ac-be88-439e-b171-fc4e7f8f3e39
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d2cf84b8-da42-48ed-9ffa-4f93da867f96 # Text Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa4b6fe8-9980-4643-ba27-20fdf3d1d926
            userCondition: null
            warning: null
            width: 100
        name: 'Podcast Tile'
        uid: cc5606dd-de31-416f-ac8c-060eee282e4c
        userCondition: null
group: null
groupChildBlockTypes: true
handle: podcastTile
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Podcast Tile'
topLevel: false
