childBlocks:
  - factoid1Up
  - factoid2Up
  - factoid3Up
  - button
conditions: null
description: ''
enabled: true
field: aefea3fc-ff45-4615-b305-9079e2cc6c44 # Page Builder: Impact Report
fieldLayouts:
  88d19629-8382-4884-bc57-eea101e263f1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 76c2555a-23b9-4d53-8c79-13892f75b970 # Factoid Description Box
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 134b27ce-1855-4e4d-954e-638f2f252f09
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4f1a3081-cb03-47eb-b862-638e1b362e22 # Image Position [L|R]
            instructions: null
            label: 'Factoid Position [L|R]'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f60ba518-2cce-4a36-a23b-c845a32d68e2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: benf\neo\fieldlayoutelements\ChildBlocksUiElement
            uid: 35351df1-24f8-4523-8bc2-4ff3a85cdaf7
            userCondition: null
        name: Factoid
        uid: 587de330-eb77-460e-868c-66194ddb60ec
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d24ab695-25c2-4078-b7e4-b936aa667ac6 # Pre-Eyebrow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10d6261c-4a23-45ce-a43f-1f64d3f85c26
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: fb633af9-99e4-499c-b90f-60a8039f3046 # Text Alignment
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: deef3565-7e16-4abc-af78-cdb0656ee038
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: e39974bd-ec97-4187-be91-a431e1a4fbd7 # Eyebrow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f040af99-b662-40e7-88f2-97f2ae483ae9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6ab970bd-1621-4c3f-8eeb-6887ac8cbb2c # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b133ab58-0865-4247-8295-fc43af7a412f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d4a66aad-fd77-4abe-97e2-a01cabc77bac # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 207f852c-7d07-486d-adc6-e8327ecb26e9
            userCondition: null
            warning: null
            width: 100
        name: Description
        uid: c517ec69-935d-40dd-9521-72609ceacd73
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 28a04878-3d6a-4889-ad36-87cce2dd449e # Padding: Top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 011794df-1f4d-4e11-bd5d-d796f3d4d74b
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 040d7db9-375b-4b41-989d-2e38c47b90f6 # Padding: Bottom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 38174939-3b81-4d9a-b092-275b586c6725
            userCondition: null
            warning: null
            width: 25
        name: 'Section Settings'
        uid: de57f9a3-357b-4a47-aca2-f5f55e28d042
        userCondition: null
group: null
groupChildBlockTypes: true
handle: textFactoid
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Text+Factoid
topLevel: true
