childBlocks: null
conditions: null
description: ''
enabled: true
field: 0ba00a47-4ce1-4c02-a3ca-61119f702d8d # Mega Menu: Links
fieldLayouts:
  fc520549-352e-45d5-b44b-d61b74895950:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d2cf84b8-da42-48ed-9ffa-4f93da867f96 # Text Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 015464fb-daf3-4882-a11c-9c1621cf6517
            userCondition: null
            warning: null
            width: 100
        name: 'Text Link'
        uid: e7e70f12-b8f9-423f-98c1-c4ba71534f50
        userCondition: null
group: null
groupChildBlockTypes: true
handle: textLink
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Text Link'
sortOrder: 2
topLevel: false
