childBlocks: null
conditions: null
description: ''
enabled: true
field: f69cfc32-4011-4eea-a32a-f5ae9fd5b24e # Page Builder: General
fieldLayouts:
  f25fffb4-d93c-4d2b-989f-e404b0555486:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'Insert two large tiles.'
            type: craft\fieldlayoutelements\Tip
            uid: 34aeedcb-8cb2-450c-9d59-dd05f47df727
            userCondition: null
          -
            elementCondition: null
            fieldUid: e11568a1-11e3-4147-ae18-1ff01fdcd4f7 # CTA Tile: Small
            instructions: null
            label: 'CTA Tile'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a5ad9d7-ea30-48f3-bd98-07578543aa63
            userCondition: null
            warning: null
            width: 100
        name: Tiles
        uid: 72d754b9-53a3-4e42-b0b0-c507b2dbb2f7
        userCondition: null
group: null
groupChildBlockTypes: true
handle: tiles2Up
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Tiles: 2-up'
topLevel: false
