childBlocks: null
conditions: null
description: ''
enabled: true
field: f69cfc32-4011-4eea-a32a-f5ae9fd5b24e # Page Builder: General
fieldLayouts:
  5a541876-c724-4189-a919-420c0c1a80ba:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a8366a49-97a6-4a33-a567-a948f6a481ac # Section ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4dfcb124-8c98-42ec-bfef-8813e07753ed
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2f76bca5-2eaf-4262-8c5d-edb7401cc84f # Video
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7337d8e7-8f1a-498a-aaea-74cdfb2e087a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4f1a3081-cb03-47eb-b862-638e1b362e22 # Image Position [L|R]
            instructions: null
            label: 'Video Position [L|R]'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a927ebb7-688a-4628-b72c-7519187e6263
            userCondition: null
            warning: null
            width: 100
        name: Video
        uid: be7cb417-7a81-41dc-8137-e2ba21499671
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: aa3d7fc1-1a22-4fff-8fe2-28dd1ab8388e # Pre-heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aacbeafe-134c-49cd-9dcd-af78dd8ea502
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 31f2b911-731f-42b5-84c6-4b2777260f2f # Section Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef83c7e8-4ccb-4882-87c8-c337810f9f79
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d4a66aad-fd77-4abe-97e2-a01cabc77bac # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3596af78-ca96-4f6c-93cf-9d6036a1c405
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 17fcc0b6-4e93-425f-9380-11c07300553d # Buttons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 84cdb674-66fe-4278-9604-66e78a3bf6d3
            userCondition: null
            warning: null
            width: 100
        name: 'Text Description'
        uid: c657ed49-78cd-4855-a5ef-c98f7f4443d3
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: dfbc0047-f74f-4940-baf3-7f9402fc918e # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3dba2601-6a86-4050-aeea-a4d585c1c702
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 28a04878-3d6a-4889-ad36-87cce2dd449e # Padding: Top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 40ffa7f9-a986-4cf9-a8ed-8a990bdf30c0
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 040d7db9-375b-4b41-989d-2e38c47b90f6 # Padding: Bottom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 04c82d98-e258-4ed7-9b8c-9fd90ea7a00a
            userCondition: null
            warning: null
            width: 25
        name: 'Section Settings'
        uid: 24af3211-7501-45b9-a6e7-a5d8c94df013
        userCondition: null
group: null
groupChildBlockTypes: true
handle: videoTextBlock
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Video+Text Block'
topLevel: true
