field: 56133272-2baa-403c-9702-0c006d9c3676 # Accordion Items
fieldLayouts:
  faa4721d-c1e4-4ad6-a7d8-2c64d1a90a95:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6eeff1eb-96ce-43ab-911f-a6e7aa97139e # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c570dece-6498-4b5a-80a9-c9a52e8ea316
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6eef926d-daad-4ff8-9cce-8ececaa4dcf4 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b96ea3d0-ed34-4d40-8656-be892ea8bce4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3a707b8e-51df-4e54-bd6c-582b9c27e28b
        userCondition: null
fields:
  6eef926d-daad-4ff8-9cce-8ececaa4dcf4: # Description
    columnSuffix: tojndmxx
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: null
    name: Description
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: false
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: true
      showUnpermittedVolumes: true
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  6eeff1eb-96ce-43ab-911f-a6e7aa97139e: # Heading
    columnSuffix: rxffmbvp
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: accordionItem
name: 'Accordion Item'
sortOrder: 1
