field: d7309e06-7ddd-4cf6-aed8-416a67ebdaf3 # Alert Bar
fieldLayouts:
  d6becf3d-9fb1-4e19-8a6d-b52146d6e32f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 67306533-298f-4596-8784-f3edc0f153cf # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d9c31413-a7ea-419b-91ce-43a5c290d24a
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 7484a8cf-c4be-407b-8553-4531823cd337 # Text Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa816ca8-c01d-4799-906e-692a286b0306
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 3125ce66-ea33-4f5f-80ed-31b397f16627 # Message
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 29c2da6e-6eaf-469b-af05-37f30b35d802
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e6667266-f158-4873-9afb-b489948c70b9
        userCondition: null
fields:
  3125ce66-ea33-4f5f-80ed-31b397f16627: # Message
    columnSuffix: ttsakzop
    contentColumnType: text
    fieldGroup: null
    handle: message
    instructions: null
    name: Message
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: false
      redactorConfig: Simple.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: true
      showUnpermittedVolumes: true
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  7484a8cf-c4be-407b-8553-4531823cd337: # Text Color
    columnSuffix: owymnhlo
    contentColumnType: string
    fieldGroup: null
    handle: textColor
    instructions: null
    name: 'Text Color'
    searchable: false
    settings:
      dataSet: 'Text Colors'
      type: dropdown
    translationKeyFormat: null
    translationMethod: none
    type: statikbe\configvaluesfield\fields\ConfigValuesFieldField
  67306533-298f-4596-8784-f3edc0f153cf: # Background Color
    columnSuffix: ogoibwjg
    contentColumnType: string
    fieldGroup: null
    handle: backgroundColor
    instructions: null
    name: 'Background Color'
    searchable: false
    settings:
      dataSet: 'Section Backgrounds'
      type: dropdown
    translationKeyFormat: null
    translationMethod: none
    type: statikbe\configvaluesfield\fields\ConfigValuesFieldField
handle: alert
name: Alert
sortOrder: 1
