field: 0774c028-80d9-40e2-a668-5558b97314d3 # Headshot Videos
fieldLayouts:
  dd551cb8-2c1d-468b-a009-f43e5969a81f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 19c27c03-7838-4358-9214-9634fe9e3970 # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1fd7fcb7-2098-4a4f-8268-e00fe084fd2e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9ddb9516-4a7b-47d9-8d0c-aa93fd335b4c # Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 81867483-5b9d-4ae8-a40c-7b7b0b934d37
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d79c352e-f405-46a0-b6cd-bdfff5e4a81e # Video
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0485475-a4d1-4a1a-8b9a-238a6e8d4348
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d702a99d-937d-42d1-803a-8fdc4e24b081
        userCondition: null
fields:
  9ddb9516-4a7b-47d9-8d0c-aa93fd335b4c: # Label
    columnSuffix: laifahns
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: null
    name: Label
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  19c27c03-7838-4358-9214-9634fe9e3970: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:ae512cd8-d6a4-49a2-b185-8ba40a87fc1e' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:ae512cd8-d6a4-49a2-b185-8ba40a87fc1e' # Images
      restrictedLocationSubpath: null
      selectionLabel: 'Add an image'
      showSiteMenu: false
      showUnpermittedFiles: true
      showUnpermittedVolumes: true
      sources:
        - 'volume:ae512cd8-d6a4-49a2-b185-8ba40a87fc1e' # Images
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  d79c352e-f405-46a0-b6cd-bdfff5e4a81e: # Video
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: video
    instructions: "1. Click the [+ Add a video] button\r\n2. Click the [EMBED] button at the bottom of the file picker popup\r\n3. Copy and paste the video URL into the field that appears\r\n4. Click [Save] button after video preview appears\r\n5. Click [Select] button at the bottom of the file picker window "
    name: Video
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:dd3266ad-0d93-46fc-89f3-e57ebce2178c' # Videos
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:ae512cd8-d6a4-49a2-b185-8ba40a87fc1e' # Images
      restrictedLocationSubpath: null
      selectionLabel: 'Add a video'
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources:
        - 'volume:dd3266ad-0d93-46fc-89f3-e57ebce2178c' # Videos
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: headshot
name: Headshot
sortOrder: 1
