field: 24a26f70-67f3-45a7-8828-d33f091c1508 # Home: Tile - Wide
fieldLayouts:
  7cf67546-5317-45fe-9e19-20ac8de4aaf9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7a533a82-4f0f-4e24-b8e2-f37bb95a4b06 # Thumbnail
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ea6d80ea-e4d2-4ccd-8cd0-705e292bdac6
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 7122cd83-09df-457d-8ea8-284328ec238f # label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1974ba1d-f724-4a30-b77f-e59d04362aad
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 38b1109c-b2b4-4a24-8273-95f4885fdbbe # Label: Custom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a3b3a0a1-98d7-472b-b6ca-68673dd210d1
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: ff81d39c-f083-4ae5-aaa1-08eabba9c8da # Icon: Custom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3e891993-fb4f-4a9b-b945-1208091a5393
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 37449807-b7fe-4e44-bc5d-f3469359b775 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fb80aac3-9a76-4d42-9531-e6c09fb25184
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c13a4a02-215c-406f-8eb0-6aaca8403db8 # CTA Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8a094be2-ee90-447c-a7c8-a2238cee9c78
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: dfd79e06-ec34-4364-a116-9f7f6a0337d0
        userCondition: null
fields:
  7a533a82-4f0f-4e24-b8e2-f37bb95a4b06: # Thumbnail
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: thumbnail
    instructions: null
    name: Thumbnail
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:ae512cd8-d6a4-49a2-b185-8ba40a87fc1e' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:ae512cd8-d6a4-49a2-b185-8ba40a87fc1e' # Images
      restrictedLocationSubpath: null
      selectionLabel: 'Add a thumbnail image'
      showSiteMenu: true
      showUnpermittedFiles: true
      showUnpermittedVolumes: true
      sources:
        - 'volume:ae512cd8-d6a4-49a2-b185-8ba40a87fc1e' # Images
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  38b1109c-b2b4-4a24-8273-95f4885fdbbe: # Label: Custom
    columnSuffix: nhanvqto
    contentColumnType: text
    fieldGroup: null
    handle: labelCustom
    instructions: null
    name: 'Label: Custom'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  7122cd83-09df-457d-8ea8-284328ec238f: # label
    columnSuffix: nvmfxgto
    contentColumnType: string
    fieldGroup: null
    handle: label
    instructions: null
    name: label
    searchable: false
    settings:
      dataSet: 'CTA Tile Labels'
      type: dropdown
    translationKeyFormat: null
    translationMethod: none
    type: statikbe\configvaluesfield\fields\ConfigValuesFieldField
  37449807-b7fe-4e44-bc5d-f3469359b775: # Heading
    columnSuffix: icklxuaz
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c13a4a02-215c-406f-8eb0-6aaca8403db8: # CTA Link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: ctaLink
    instructions: null
    name: 'CTA Link'
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: true
      autoNoReferrer: true
      customTextMaxLength: 0
      customTextRequired: true
      defaultLinkName: entry
      defaultText: ''
      enableAllLinkTypes: false
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: true
        email:
          allowAliases: false
          disableValidation: false
          enabled: false
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: false
        url:
          allowAliases: false
          disableValidation: false
          enabled: false
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: none
    type: lenz\linkfield\fields\LinkField
  ff81d39c-f083-4ae5-aaa1-08eabba9c8da: # Icon: Custom
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: iconCustom
    instructions: null
    name: 'Icon: Custom'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: false
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:ae512cd8-d6a4-49a2-b185-8ba40a87fc1e' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:ae512cd8-d6a4-49a2-b185-8ba40a87fc1e' # Images
      restrictedLocationSubpath: null
      selectionLabel: 'Add an icon'
      showSiteMenu: false
      showUnpermittedFiles: true
      showUnpermittedVolumes: true
      sources:
        - 'volume:ae512cd8-d6a4-49a2-b185-8ba40a87fc1e' # Images
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: imageTile
name: 'Image Tile'
sortOrder: 2
