field: 6caec3d2-766a-490b-9491-7b784243b1d4 # Mega Menu: CTAs
fieldLayouts:
  f1d65752-9882-43e4-8a13-4d61f92e6cba:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0d346e5c-0f60-4911-9492-f7c3c2b17328 # Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1e501ae9-c3bb-4a4e-b6a5-ed48680fc02d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 49625178-5103-4a90-a56a-0e9582480d8e
        userCondition: null
fields:
  0d346e5c-0f60-4911-9492-f7c3c2b17328: # Label
    columnSuffix: zsolemia
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: null
    name: Label
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: label
name: Label
sortOrder: 1
