field: 479ec005-6f3d-4922-b8e5-da10aad75bdc
fieldLayouts:
  2a14f672-bedc-4626-aeb9-117a75dec677:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 58712ece-7721-4366-900b-2cc4858ea5e0
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c49d243b-54ba-47c2-aa53-a2fd8d9883ec
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 72c21d48-1ae1-46e6-a4d8-57c63a5eb883
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 992b5a16-7714-455a-96d2-8d4d69808cfb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8a5f7a26-0e88-4d83-8d0e-2f3d9a1193fd
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e35eb237-bf0c-4b86-9a61-c13d9516887d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: eaf0d64e-a5d2-48e0-9547-b790b9262fe3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 243da8d0-5431-48aa-ad6f-dd88da142c58
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 72c72f08-418a-4a74-b195-0cedce984b4e
        userCondition: null
fields:
  8a5f7a26-0e88-4d83-8d0e-2f3d9a1193fd:
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: table
    instructions: null
    name: Table
    searchable: true
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: 1
      selectionLabel: 'Add a table'
      showSiteMenu: true
      sources:
        - 'section:115274b7-184f-4d2c-898d-b1f9504e6aef'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  72c21d48-1ae1-46e6-a4d8-57c63a5eb883:
    columnSuffix: dyzraibf
    contentColumnType: text
    fieldGroup: null
    handle: subheading
    instructions: 'Override pre-defined subheading'
    name: Subheading
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  58712ece-7721-4366-900b-2cc4858ea5e0:
    columnSuffix: yryrawzk
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: 'Override pre-defined heading'
    name: Heading
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  eaf0d64e-a5d2-48e0-9547-b790b9262fe3:
    columnSuffix: yjityhxe
    contentColumnType: text
    fieldGroup: null
    handle: tableFooter
    instructions: 'Override pre-defined table footer'
    name: 'Table Footer'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: false
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: true
      showUnpermittedVolumes: true
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: preDefinedTable
name: 'Pre-defined Table'
sortOrder: 1
