field: 4f0d1ee0-d0f1-4aea-a5cb-42ce275e72e4 # Popup
fieldLayouts:
  ed811068-8473-4ad5-84e7-4c7a95edfbb1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7e2349b9-7b97-4940-8c4a-a4f5c484dc4f # Modal Size
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd579443-681b-40d7-8552-f8ffc4e07608
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 7e18b560-b806-44a3-9917-0816b0ee3517 # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: af9cfd22-afc7-4d66-89be-4bc582f7bc05
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 162c87c8-b7da-4a3a-ad1d-a0d6745835f9 # Text Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 254c7528-a729-4efa-ba80-d82a5ce0ccf8
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: c32f12ef-294f-48af-bc53-4f27a6cd908a # Link Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f1bee181-7eb3-40d7-b2c3-5ddb942e0836
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 62383ad3-0d0f-4149-ab26-742e25c861ba # Text Alignment
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca794718-fc09-44eb-9959-1e602c95fdc1
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: a15339e9-4539-4323-8a32-e6d033af151e # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dc40344a-a743-4a0b-9a1e-30a2c57e305c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 75ffc990-9c9a-40b8-a214-0ae30912f453 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b53e5448-80fc-4bbe-abc5-7a5020fe0b8b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f8186410-e438-40ee-8131-7f31ebcd0fa9 # Embed Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f18f42b-bdb2-4b7c-8699-c384ad5bfa7b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e1a7c463-bcb1-488f-8036-48c88e6ed43b # Buttons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e1c4fa08-9820-4eb3-899b-dfc880d98527
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b62c3e3c-f423-4e26-aa2b-0e940d2ff296
        userCondition: null
fields:
  7e18b560-b806-44a3-9917-0816b0ee3517: # Background Color
    columnSuffix: ktmhzmlr
    contentColumnType: string
    fieldGroup: null
    handle: backgroundColor
    instructions: null
    name: 'Background Color'
    searchable: false
    settings:
      dataSet: 'Section Backgrounds'
      type: dropdown
    translationKeyFormat: null
    translationMethod: none
    type: statikbe\configvaluesfield\fields\ConfigValuesFieldField
  7e2349b9-7b97-4940-8c4a-a4f5c484dc4f: # Modal Size
    columnSuffix: pqppkrng
    contentColumnType: string(2)
    fieldGroup: null
    handle: modalSize
    instructions: null
    name: 'Modal Size'
    searchable: false
    settings:
      columnType: null
      options:
        -
          __assoc__:
            -
              - label
              - SM
            -
              - value
              - sm
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '--'
            -
              - value
              - ''
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - LG
            -
              - value
              - lg
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - XL
            -
              - value
              - xl
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  75ffc990-9c9a-40b8-a214-0ae30912f453: # Description
    columnSuffix: stglvgif
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: null
    name: Description
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: a9e9ac13-8b36-4627-b8f4-43f5e99aede5 # Responsive: Large
      manualConfig: ''
      purifierConfig: null
      purifyHtml: false
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: true
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  162c87c8-b7da-4a3a-ad1d-a0d6745835f9: # Text Color
    columnSuffix: nixwunvf
    contentColumnType: string
    fieldGroup: null
    handle: textColor
    instructions: null
    name: 'Text Color'
    searchable: false
    settings:
      dataSet: 'Text Colors'
      type: dropdown
    translationKeyFormat: null
    translationMethod: none
    type: statikbe\configvaluesfield\fields\ConfigValuesFieldField
  62383ad3-0d0f-4149-ab26-742e25c861ba: # Text Alignment
    columnSuffix: udezdfgy
    contentColumnType: string(11)
    fieldGroup: null
    handle: textAlignment
    instructions: null
    name: 'Text Alignment'
    searchable: false
    settings:
      columnType: null
      options:
        -
          __assoc__:
            -
              - label
              - Left
            -
              - value
              - text-start
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Center
            -
              - value
              - text-center
            -
              - default
              - '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  a15339e9-4539-4323-8a32-e6d033af151e: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: false
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:ae512cd8-d6a4-49a2-b185-8ba40a87fc1e' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:ae512cd8-d6a4-49a2-b185-8ba40a87fc1e' # Images
      restrictedLocationSubpath: null
      selectionLabel: 'Add an image'
      showSiteMenu: true
      showUnpermittedFiles: true
      showUnpermittedVolumes: true
      sources:
        - 'volume:ae512cd8-d6a4-49a2-b185-8ba40a87fc1e' # Images
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  c32f12ef-294f-48af-bc53-4f27a6cd908a: # Link Color
    columnSuffix: ywprjhge
    contentColumnType: string
    fieldGroup: null
    handle: linkColor
    instructions: null
    name: 'Link Color'
    searchable: false
    settings:
      dataSet: 'CSS Color Classes'
      type: dropdown
    translationKeyFormat: null
    translationMethod: none
    type: statikbe\configvaluesfield\fields\ConfigValuesFieldField
  e1a7c463-bcb1-488f-8036-48c88e6ed43b: # Buttons
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: buttons
    instructions: null
    name: Buttons
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 1271385943
      columns:
        __assoc__:
          -
            - fcb52c22-c183-41f8-8e7b-eba92f387d0d # Button
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 348b4f5c-bf77-4164-a783-c2dd57770990 # Button Style
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_17_buttons}}'
      fieldLayout: matrix
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: 'Add a button'
      staticField: null
    translationKeyFormat: null
    translationMethod: none
    type: verbb\supertable\fields\SuperTableField
  f8186410-e438-40ee-8131-7f31ebcd0fa9: # Embed Code
    columnSuffix: hbmavtgf
    contentColumnType: text
    fieldGroup: null
    handle: embedCode
    instructions: null
    name: 'Embed Code'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: true
      columnType: null
      initialRows: 2
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: simple
name: Simple
sortOrder: 1
