field: 11a02d8c-6388-4bec-914d-2e386b4d1101 # Legal Links
fieldLayouts:
  2c0e92f5-2dce-4b8e-bc36-f0038a91de9b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ff02b5d9-24b9-4da0-858a-ad8253a72bb3 # Text Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 85db7bee-9b8a-4a9f-9c51-4ce24145f8c5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 91684d8a-62f4-4faa-96ae-7e22e1d3633e
        userCondition: null
fields:
  ff02b5d9-24b9-4da0-858a-ad8253a72bb3: # Text Link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: textLink
    instructions: null
    name: 'Text Link'
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: true
      autoNoReferrer: true
      customTextMaxLength: 0
      customTextRequired: false
      defaultLinkName: entry
      defaultText: ''
      enableAllLinkTypes: false
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: true
        email:
          allowAliases: false
          disableValidation: false
          enabled: true
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: true
        url:
          allowAliases: false
          disableValidation: false
          enabled: false
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: none
    type: lenz\linkfield\fields\LinkField
handle: textLink
name: 'Text Link'
sortOrder: 1
