allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  faa4721d-c1e4-4ad6-a7d8-2c64d1a90a95:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:c570dece-6498-4b5a-80a9-c9a52e8ea316'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6eeff1eb-96ce-43ab-911f-a6e7aa97139e # Accordion Items - Accordion Item - Heading
            handle: heading
            instructions: null
            label: Heading
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c570dece-6498-4b5a-80a9-c9a52e8ea316
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6eef926d-daad-4ff8-9cce-8ececaa4dcf4 # Accordion Items - Accordion Item - Description
            handle: description
            instructions: null
            label: Description
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b96ea3d0-ed34-4d40-8656-be892ea8bce4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3a707b8e-51df-4e54-bd6c-582b9c27e28b
        userCondition: null
    thumbFieldKey: null
handle: accordionItem
hasTitleField: false
icon: null
name: 'Accordion Item'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
