allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  3724d752-86dd-497f-965a-614757078c63:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a8aa09ad-74e8-4ad5-8d2d-7739c2b90664 # Popup - Side By Side - Buttons - Button
            handle: button
            instructions: null
            label: Button
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 73872d8d-5384-493a-bf26-86faede0b53f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: d67baeb3-d18c-4287-8ce5-83a70d6f91d9 # Popup - Side By Side - Buttons - Button Style
            handle: buttonStyle
            instructions: null
            label: 'Button Style'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0095993-7935-4054-94f5-defb3422f9b7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0e0bb899-22f2-40ee-a957-8a249260e546
        userCondition: null
    thumbFieldKey: null
handle: buttons3Block
hasTitleField: false
icon: null
name: 'Popup - Side By Side - Buttons Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
