allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  ebd6b1d0-b479-4534-b7d8-13e282ccc062:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: fcb52c22-c183-41f8-8e7b-eba92f387d0d # Popup - Simple - Buttons - Button
            handle: button
            instructions: null
            label: Button
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 58b32012-d4b3-404a-b6b2-506578b1f1d2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 348b4f5c-bf77-4164-a783-c2dd57770990 # Popup - Simple - Buttons - Button Style
            handle: buttonStyle
            instructions: null
            label: 'Button Style'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 278168ca-9c53-4384-be34-b1852048a904
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2f9164e7-bae2-4cf8-9502-19cf7f85955e
        userCondition: null
    thumbFieldKey: null
handle: buttons2Block
hasTitleField: false
icon: null
name: 'Popup - Simple - Buttons Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
