allowLineBreaksInTitles: false
color: teal
description: null
fieldLayouts:
  73e600a7-9193-4c1f-8ee7-6a85decc3b53:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-04-17T22:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 928102e8-1c42-4c1a-ae97-8d89293e8fff
            handle: embedCode
            instructions: null
            label: 'Embed Code'
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b0002001-0001-0001-0001-000000000001
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 279fc8ff-7f18-4771-a9e1-8b4635b3c61f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-04-17T22:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 013b54c6-1959-4a84-bdb3-49b726c92a78
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b0002001-0001-0001-0001-000000000002
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-17T22:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 37f0d1ef-eecb-4fcf-a828-0fb56d8130cf
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b0002001-0001-0001-0001-000000000003
            userCondition: null
            warning: null
            width: 50
        name: 'Section Settings'
        uid: c40c3316-51fd-4b0e-a8b7-52f2efcab234
        userCondition: null
    thumbFieldKey: null
handle: cbEmbedCodeBlock
hasTitleField: false
icon: rectangle-code
name: 'CB: Embed Code Block'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
