allowLineBreaksInTitles: false
color: teal
description: null
fieldLayouts:
  10765b81-410b-4465-b074-8dd0aa7e77df:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-04-17T22:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 61dd4608-bc61-4fea-81b6-473b7716998d
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0003001-0001-0001-0001-000000000001
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-04-17T22:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6181e2c8-7e70-4113-bc0c-3febe696d670
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0003001-0001-0001-0001-000000000002
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: a1dd3788-75f4-4641-88de-faeb3ab9d63e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-04-17T22:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 013b54c6-1959-4a84-bdb3-49b726c92a78
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0003001-0001-0001-0001-000000000003
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-17T22:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 37f0d1ef-eecb-4fcf-a828-0fb56d8130cf
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0003001-0001-0001-0001-000000000004
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2026-04-17T22:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f6a87a85-604e-4d5c-9266-cb31a3551324
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0003001-0001-0001-0001-000000000005
            userCondition: null
            warning: null
            width: 25
        name: 'Section Settings'
        uid: 33ec6020-f865-4780-aa6c-6a78e78d14c8
        userCondition: null
    thumbFieldKey: null
handle: cbImageBlock
hasTitleField: false
icon: image-landscape
name: 'CB: Image Block'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
