allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  8471f1ca-f929-4338-9577-09ce381a828a:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:9713dc0b-aece-42e3-9d29-4d7101bb6909'
      - 'layoutElement:328ecab7-bd38-4d50-8c63-661a0bf37ac8'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6e1fd6d5-5ab2-4bee-8393-d541afe51eea
            handle: heading
            instructions: null
            label: Heading
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9713dc0b-aece-42e3-9d29-4d7101bb6909
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 9e28f3c9-7883-4de5-93ef-fcf8ed4ca639
            handle: subheading
            instructions: null
            label: Subheading
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 328ecab7-bd38-4d50-8c63-661a0bf37ac8
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: d0098f21-2d27-4c01-a70b-b9f036b1d94b
            handle: null
            instructions: null
            label: 'Custom Table'
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: be928742-f146-4f2b-b097-658ccf0d3f13
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 3cd86bf3-6755-432c-a7cd-8fdb85ad0ccb # Data Tables - Custom Table - Table Footer
            handle: tableFooter
            instructions: null
            label: 'Table Footer'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3b18510b-5379-4be5-b63f-8ddc802ba4e1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: df0fef86-6c35-47a5-84fa-7e4da4a42f51
        userCondition: null
    thumbFieldKey: null
handle: customTable
hasTitleField: false
icon: null
name: 'Custom Table'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
