allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  ac4ed749-ab9a-4787-b64e-1b4a0d8fbacd:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: b8904bf4-d4cd-4023-963d-3dbcebfabb78
            handle: heading
            instructions: null
            label: Heading
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a0a09df5-ae2f-4a93-ba1a-869771d28706
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 86c0cfb0-f792-48aa-aef6-7f1df1dac5b1
            handle: subheading
            instructions: null
            label: Subheading
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7e9c38ca-6c6c-4ae9-a3c1-4bf6b85b48ae
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 0fbd0f44-e701-4761-805c-fc232ba797b4 # Factoid Description Box - Description
            handle: description
            instructions: null
            label: Description
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 885658a7-bbd9-4545-a3b4-93c77fb354e5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 5ca729bf-6b89-4d06-931b-db7f8b086ec6
            handle: backgroundColor
            instructions: null
            label: 'Background Color'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2b7af1db-fd9f-409b-8ff4-00387c2f06cd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a2ae2fe6-4b2e-46b7-ba36-a796db1860b9
        userCondition: null
    thumbFieldKey: null
handle: factoidDescriptionBoxBlock
hasTitleField: false
icon: null
name: 'Factoid Description Box Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
