fieldLayouts:
  4d2dddb8-fbbd-4b13-98d8-b38368456e71:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0663fa6e-673e-41bc-9e6c-fa6c6d389cda
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\EmptyFieldConditionRule
                  fieldUid: 23354ff5-9e58-4f25-a8b1-77c6f7b7b7d8
                  operator: notempty
                  uid: ce2a30e5-b6d9-4ad0-bedb-79366af5f2bb
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 89795803-5837-4d6f-855d-1ae3c3980e55
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 53db6c21-6029-4bcd-9f4d-f2c0452b9d73
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: eaa2de37-8703-4880-aa20-3f0222fa32dc
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1922cd71-2f89-458a-986d-28d7e4c5b1cd
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 23354ff5-9e58-4f25-a8b1-77c6f7b7b7d8
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7a9d92a6-1933-4af3-bacb-5841c12630f6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f69cfc32-4011-4eea-a32a-f5ae9fd5b24e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6fcce2eb-c42a-49fc-aef7-2af18b7fced0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 65ca309b-0738-4f16-881d-dc7ddb88c6c3
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e9b0d2b3-481f-4b12-bf3c-4fc241f7e6f8
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f0622dc7-c5e2-46ae-bfba-af530c5df9b5
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: e8a7568f-e18e-4496-8dc3-9c16a606570a
        userCondition: null
handle: general
hasTitleField: true
name: General
section: 92cb8d3c-2b19-477d-ad39-fe24ade9438c
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
