allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  ac482144-0af6-4767-90da-4d1d39e61395:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 643e4c17-f296-47ae-8806-45847ebda838
            handle: null
            instructions: null
            label: 'Pre Heading'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 23639c18-8cb3-4f6e-83df-4764f1f41c0f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: ab39e5a8-9059-4669-8998-c898c3c7ed89
            handle: heading
            instructions: null
            label: Heading
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c9a8f7b-7c6f-4169-94af-776247712f21
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 0d19f0b1-727c-4654-9f11-09b986093f3d
            handle: ctaLink
            instructions: null
            label: 'CTA Link'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3b4f00ae-5294-434a-b4a4-2c31c13ac710
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a6ec9725-02c5-48b7-9b8b-773e95ca5395
        userCondition: null
    thumbFieldKey: null
handle: homeIntroBlock
hasTitleField: false
icon: null
name: 'Home: Intro Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
