fieldLayouts:
  7a31c040-9fb5-457b-8317-86c513fbd5df:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b3cb9375-5658-4180-8dc3-bf91b354d09c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b00ccfa2-369c-471f-ae02-ae5ed2a9bae6 # Thumbnail
            instructions: 'Choose a thumbnail image for the preview card'
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6144b3a2-0c11-469c-96fb-57a80cbe4ae1
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 6b671144-8ff1-4b84-9c9e-d0b03e00adfd # News Category
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0789a454-6544-4e84-8968-67f4024b60be
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 6ab970bd-1621-4c3f-8eeb-6887ac8cbb2c # Heading
            instructions: 'Override entry title on preview card'
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 390e8402-7350-4d75-869e-0e15cb3def47
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cdb162a5-f0d2-429b-b5ac-588fc77a48da # Summary
            instructions: 'Short summary for the preview card'
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1263907a-9108-457b-80e7-3ee4c7eaa687
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d2cf84b8-da42-48ed-9ffa-4f93da867f96 # Text Link
            instructions: null
            label: 'Link to this resource instead of an article detail page'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4cd8cc7a-3a3d-4252-8fab-197a525817d7
            userCondition: null
            warning: null
            width: 100
        name: 'Preview Card'
        uid: b98a7140-70fa-4174-81b7-36c0bd5b8f57
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0914ee96-13fc-4737-ae93-8ab00d611b35 # Page Builder: Blog
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fbd7ada3-27cd-4c2c-bb1b-01cd62e6329c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d55fd1ed-fb9d-48b1-aac6-523eb0238a57
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e9b0d2b3-481f-4b12-bf3c-4fc241f7e6f8 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d5f28b0a-11c5-4cc9-820b-8141ae4b231e
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: b3964abc-6684-445e-b836-8e6b3f677b18
        userCondition: null
handle: news
hasTitleField: true
name: News
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
