allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  e52912fe-4e89-4536-b4e9-3a4e67cc8037:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: dcce62b3-2650-4939-a381-0fcc22c0d942 # Open An Account Table - Church or Agency
            handle: null
            instructions: null
            label: 'Church or Agency'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 874afa9f-518a-4e26-87ed-635401d86465
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 39b454aa-6c69-4f49-b375-8bf7b6f4ce23 # Open An Account Table - Nonprofits
            handle: null
            instructions: null
            label: Nonprofits
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0071240b-a2e7-45a4-b68d-eab7427f13fb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: af55010a-5968-4c25-91f8-dffbcb72d4db # Open An Account Table - Individuals
            handle: null
            instructions: null
            label: Individuals
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fba762e2-3251-4476-803f-d94e4cb98b81
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4177bfe7-806c-4104-8b4e-c096164518a2
        userCondition: null
    thumbFieldKey: null
handle: openAnAccountTableBlock
hasTitleField: false
icon: null
name: 'Open An Account Table Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
