allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  ed811068-8473-4ad5-84e7-4c7a95edfbb1:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:cd579443-681b-40d7-8552-f8ffc4e07608'
      - 'layoutElement:af9cfd22-afc7-4d66-89be-4bc582f7bc05'
      - 'layoutElement:254c7528-a729-4efa-ba80-d82a5ce0ccf8'
      - 'layoutElement:f1bee181-7eb3-40d7-b2c3-5ddb942e0836'
      - 'layoutElement:ca794718-fc09-44eb-9959-1e602c95fdc1'
      - 'layoutElement:5f18f42b-bdb2-4b7c-8699-c384ad5bfa7b'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7e2349b9-7b97-4940-8c4a-a4f5c484dc4f # Popup - Simple - Modal Size
            handle: null
            instructions: null
            label: 'Modal Size'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd579443-681b-40d7-8552-f8ffc4e07608
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7e18b560-b806-44a3-9917-0816b0ee3517 # Popup - Simple - Background Color
            handle: backgroundColor
            instructions: null
            label: 'Background Color'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: af9cfd22-afc7-4d66-89be-4bc582f7bc05
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 162c87c8-b7da-4a3a-ad1d-a0d6745835f9 # Popup - Simple - Text Color
            handle: textColor
            instructions: null
            label: 'Text Color'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 254c7528-a729-4efa-ba80-d82a5ce0ccf8
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c32f12ef-294f-48af-bc53-4f27a6cd908a # Popup - Simple - Link Color
            handle: null
            instructions: null
            label: 'Link Color'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f1bee181-7eb3-40d7-b2c3-5ddb942e0836
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 62383ad3-0d0f-4149-ab26-742e25c861ba # Popup - Simple - Text Alignment
            handle: textAlignment
            instructions: null
            label: 'Text Alignment'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca794718-fc09-44eb-9959-1e602c95fdc1
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a15339e9-4539-4323-8a32-e6d033af151e # Popup - Simple - Image
            handle: image
            instructions: null
            label: Image
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dc40344a-a743-4a0b-9a1e-30a2c57e305c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 75ffc990-9c9a-40b8-a214-0ae30912f453 # Popup - Simple - Description
            handle: description
            instructions: null
            label: Description
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b53e5448-80fc-4bbe-abc5-7a5020fe0b8b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f8186410-e438-40ee-8131-7f31ebcd0fa9 # Popup - Simple - Embed Code
            handle: embedCode
            instructions: null
            label: 'Embed Code'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f18f42b-bdb2-4b7c-8699-c384ad5bfa7b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e1a7c463-bcb1-488f-8036-48c88e6ed43b # Popup - Simple - Buttons
            handle: buttons
            instructions: null
            label: Buttons
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e1c4fa08-9820-4eb3-899b-dfc880d98527
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b62c3e3c-f423-4e26-aa2b-0e940d2ff296
        userCondition: null
    thumbFieldKey: 'layoutElement:dc40344a-a743-4a0b-9a1e-30a2c57e305c'
handle: simple
hasTitleField: false
icon: null
name: Simple
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
