allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  7fa674ce-0a52-4efa-96e7-6472a0e5ede6:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:6ead2334-4ca9-408f-a5e6-fee10a0ce82b'
      - 'layoutElement:bdcce914-b0af-4ef5-8cd4-fe988cd66b0b'
      - 'layoutElement:f866af9a-7b42-476d-b407-adc6db3ca88b'
      - 'layoutElement:0a7b9517-3ed9-4953-8c3d-2fce66c20b4d'
      - 'layoutElement:85726a47-07ea-4a88-b179-187604bdbd2e'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 8cf524a9-c788-4109-8c27-b973b5da1c8b
            handle: image
            instructions: null
            label: Image
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 16ec6cb3-79c0-4643-8004-f2d581247695
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 148b8944-2e50-42a9-9275-0f8b85677134
            handle: null
            instructions: null
            label: 'Stack Image on Mobile'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6ead2334-4ca9-408f-a5e6-fee10a0ce82b
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c45223e5-4822-4ae1-b1a8-0a0e1ef27aa6
            handle: label
            instructions: null
            label: Label
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bdcce914-b0af-4ef5-8cd4-fe988cd66b0b
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 08a4604d-4fdb-476b-b82c-88ef59973d9e
            handle: labelCustom
            instructions: null
            label: 'Label: Custom'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f866af9a-7b42-476d-b407-adc6db3ca88b
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c937445d-2edd-4336-b195-241254cef98a
            handle: iconCustom
            instructions: null
            label: 'Icon: Custom'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0a7b9517-3ed9-4953-8c3d-2fce66c20b4d
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 5d256d74-c235-43c7-aa5c-7df02909be2a
            handle: heading
            instructions: null
            label: Heading
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 85726a47-07ea-4a88-b179-187604bdbd2e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 3b51443f-4e3e-4232-8ca5-f70fda28a3c2
            handle: null
            instructions: null
            label: Link
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 63644b5c-b98d-4501-9793-7019e0cd2918
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4c20fe74-dfcc-4c82-8f88-33d032ef5292
        userCondition: null
    thumbFieldKey: 'layoutElement:16ec6cb3-79c0-4643-8004-f2d581247695'
handle: tile2
hasTitleField: false
icon: null
name: Tile
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
