allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  8ebe701b-adde-4c20-a8d0-f19709d07121:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:56093b1c-1e08-4fb4-918d-73567e0ed5c7'
      - 'layoutElement:fc6d515d-6bc5-4fce-9812-1943cb374f1c'
      - 'layoutElement:dcc2b34d-61c9-4c7a-bebc-2135b3ba5001'
      - 'layoutElement:7d0ad05d-53ba-4b50-9a72-5eb1f3d6a003'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 18834ccd-54b8-4774-a03c-b16f65a84197
            handle: thumbnail
            instructions: null
            label: Thumbnail
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 58732d6f-b3fc-4bf0-a30c-29c4b8d0251d
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 403b04cf-f24a-4706-8842-0ecd144931b6
            handle: null
            instructions: null
            label: Label
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 56093b1c-1e08-4fb4-918d-73567e0ed5c7
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: fae047fe-30da-49d5-b8da-b1d6adafd530
            handle: null
            instructions: null
            label: 'Label: Custom'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fc6d515d-6bc5-4fce-9812-1943cb374f1c
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: aec4351f-8a70-4278-9846-54ad19f795fc
            handle: null
            instructions: null
            label: 'Icon: Custom'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dcc2b34d-61c9-4c7a-bebc-2135b3ba5001
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 9030c997-69e7-4a71-b846-fdadd3c6112f
            handle: heading
            instructions: null
            label: Heading
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7d0ad05d-53ba-4b50-9a72-5eb1f3d6a003
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c89855dd-2f3d-435d-a111-48b28771ff93
            handle: null
            instructions: null
            label: 'CTA Link'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3e6f3162-c36e-47d7-a0ed-0b5039e62e4f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a4e26f0a-6fb3-4710-84ce-e5e098d4f764
        userCondition: null
    thumbFieldKey: 'layoutElement:58732d6f-b3fc-4bf0-a30c-29c4b8d0251d'
handle: tile
hasTitleField: false
icon: null
name: Tile
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
