allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  9b0a8eec-17d3-458a-8eb4-360216a816fc:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:606692b5-540b-4a3e-b56f-e5c5b766cfb9'
      - 'layoutElement:5cc7edee-567a-4216-ad3d-ed0d9ca68d52'
      - 'layoutElement:54c2d01c-7541-4557-beb8-ad4815fabb4b'
      - 'layoutElement:ca588bd1-be1c-4e89-8664-c2619fe5c9eb'
      - 'layoutElement:36700fb8-816b-4a20-b4dd-487991c7f76a'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 251036cc-4dfd-4b0f-9823-b109a413bd0b # CTA Tile: Small - Tile - Image
            handle: image
            instructions: null
            label: Image
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e8c2be9a-24bf-4bc7-a7b5-1a565e21e08d
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: dba75db4-1559-48ba-b4d4-a5e5738429a4 # CTA Tile: Small - Tile - Stack Image on Mobile
            handle: stackImageOnMobile
            instructions: null
            label: 'Stack Image on Mobile'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 606692b5-540b-4a3e-b56f-e5c5b766cfb9
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 160cd5ce-bdfd-4507-b851-369a31a5bbb6 # CTA Tile: Small - Tile - Label
            handle: label
            instructions: null
            label: Label
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5cc7edee-567a-4216-ad3d-ed0d9ca68d52
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 8cccdb1c-6473-404a-9289-b9a52343d552 # CTA Tile: Small - Tile - Label: Custom
            handle: labelCustom
            instructions: null
            label: 'Label: Custom'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 54c2d01c-7541-4557-beb8-ad4815fabb4b
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 3b6ab5b3-228a-4f9a-b6ba-5958d0d9daf2 # CTA Tile: Small - Tile - Icon: Custom
            handle: iconCustom
            instructions: null
            label: 'Icon: Custom'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca588bd1-be1c-4e89-8664-c2619fe5c9eb
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: baddf677-8996-4c34-b436-ea8341d9bed3 # CTA Tile: Small - Tile - Heading
            handle: heading
            instructions: null
            label: Heading
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 36700fb8-816b-4a20-b4dd-487991c7f76a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 40fb54cb-b959-40bc-8123-44ac2a4c5aa2 # CTA Tile: Small - Tile - Link
            handle: tileLink
            instructions: null
            label: Link
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e3d6dfc0-d641-4389-9f47-ac3516b88b0e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ea398104-dad5-4eb7-aa2b-a5c43f8f694f
        userCondition: null
    thumbFieldKey: 'layoutElement:e8c2be9a-24bf-4bc7-a7b5-1a565e21e08d'
handle: tile3
hasTitleField: false
icon: null
name: Tile
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
