allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  d0b547f6-3747-4255-9f83-81f97faeac1c:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:8bf00eff-e5c6-4299-a318-8be0884c9d71'
      - 'layoutElement:930c6e46-26e4-4323-b975-7deac6d03696'
      - 'layoutElement:ebb07b3e-ab67-405d-a722-1cf6bb40efc6'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 4d7096da-e00f-4539-976f-2ab6e40967b7 # Home: Tile - Wide - Video Tile - Thumbnail
            handle: thumbnail
            instructions: null
            label: Thumbnail
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b5fd3d09-2d5b-4d2b-8dfa-65e9f3356785
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: d46a26f8-acd0-4f06-8f57-f8e755cbcddb # Home: Tile - Wide - Video Tile - Label
            handle: label
            instructions: null
            label: Label
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8bf00eff-e5c6-4299-a318-8be0884c9d71
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: ab7e2d93-36c3-4838-bcb0-b9378b70308a # Home: Tile - Wide - Video Tile - Heading
            handle: heading
            instructions: null
            label: Heading
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 930c6e46-26e4-4323-b975-7deac6d03696
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 74ee5a5e-4ff2-4cf1-b268-c3c2ff67c2b9 # Home: Tile - Wide - Video Tile - Video
            handle: video
            instructions: null
            label: Video
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ebb07b3e-ab67-405d-a722-1cf6bb40efc6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 43637cf7-8578-4d01-a546-810990b395df
        userCondition: null
    thumbFieldKey: 'layoutElement:b5fd3d09-2d5b-4d2b-8dfa-65e9f3356785'
handle: videoTile
hasTitleField: false
icon: null
name: 'Video Tile'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
