childBlocks: null
conditions: null
description: ''
enabled: true
field: f69cfc32-4011-4eea-a32a-f5ae9fd5b24e # Page Builder: General
fieldLayouts:
  ea2ae4d8-5826-4b35-84a7-07320928ca48:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a8366a49-97a6-4a33-a567-a948f6a481ac # Section ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6c4179d2-c663-4c43-965b-1ca98383c82d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 55f89f73-30c8-4eeb-b491-a0da78da6657 # Text Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 460de7d4-01e9-4b2b-8c8a-f40a8598f92f
            userCondition: null
            warning: null
            width: 50
          -
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'Contact form will be shown to the right of this text description.'
            type: craft\fieldlayoutelements\Tip
            uid: 014fadda-7061-429c-a500-92d3c36eb29f
            userCondition: null
          -
            elementCondition: null
            fieldUid: aa3d7fc1-1a22-4fff-8fe2-28dd1ab8388e # Pre-heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 87022131-e4c4-4a1e-b074-79ca8f86727e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 31f2b911-731f-42b5-84c6-4b2777260f2f # Section Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 57c0aa3e-e972-4914-bf36-79e1e0d80682
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d4a66aad-fd77-4abe-97e2-a01cabc77bac # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0e1002a0-bd1e-4fae-9982-3d7631c9d34f
            userCondition: null
            warning: null
            width: 100
        name: 'Text Description'
        uid: 85fc8dce-0fe3-4b14-98fe-7945e7f1d489
        userCondition: null
group: 2734260c-14b6-412b-a372-5a4ee016497a # Media
groupChildBlockTypes: true
handle: contactFormBlock
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Contact Form Block'
topLevel: true
