childBlocks:
  - largeSmallSmall
  - smallSmallLarge
conditions: null
description: ''
enabled: true
field: 23354ff5-9e58-4f25-a8b1-77c6f7b7b7d8
fieldLayouts:
  c678e22f-1d4f-4829-9c87-407b5b3b92ce:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: aa3d7fc1-1a22-4fff-8fe2-28dd1ab8388e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2fb69d61-b731-4fe9-b7ae-d10f500adaf1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6ab970bd-1621-4c3f-8eeb-6887ac8cbb2c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 14eebdef-e498-4707-9ca2-9d416b3ada28
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d4a66aad-fd77-4abe-97e2-a01cabc77bac
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed79d63b-b0cf-498b-a52e-99f863e77594
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8d53efd7-98eb-40ec-a000-4b904766072d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 823e7fc7-88a3-455b-a297-7ffbf9197990
            userCondition: null
            warning: null
            width: 100
        name: 'Intro Text'
        uid: bf13238b-0a68-4f5a-86bb-43a4becebc55
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 040d7db9-375b-4b41-989d-2e38c47b90f6
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4cae26b3-825b-4149-a6b4-698420140ac6
            userCondition: null
            warning: null
            width: 100
        name: 'Section Settings'
        uid: b44d9f64-7a52-4bba-80e5-e0e2cc4e8964
        userCondition: null
group: null
groupChildBlockTypes: true
handle: ctaTiles
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 2
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'CTA Tiles'
topLevel: true
