childBlocks: null
conditions: null
description: ''
enabled: true
field: f69cfc32-4011-4eea-a32a-f5ae9fd5b24e
fieldLayouts:
  192a5d27-e1ad-478c-996e-304c372d71c4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a8366a49-97a6-4a33-a567-a948f6a481ac
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0904ef13-5d30-4756-92ec-97b983f8ea6c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 865ca38f-50ad-4e67-9a95-bd05ae709908
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6fc912fc-b372-4214-944f-f4308e9f9362
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d31b22a1-618f-476c-b687-7938d3c9defc
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: dfbc0047-f74f-4940-baf3-7f9402fc918e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2c5d8d45-2f1e-4808-80d5-c8d548603b51
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 28a04878-3d6a-4889-ad36-87cce2dd449e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 30224694-2769-4f1f-b9bd-92f1e8115996
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 040d7db9-375b-4b41-989d-2e38c47b90f6
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 93ba9914-8f43-48c8-8dfb-399d7b97fe23
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 12a86971-9af3-496d-9a73-1f277506afaa
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 340ad59d-c160-40d6-ba6e-ab8188b34719
            userCondition: null
            warning: null
            width: 25
        name: 'Section Settings'
        uid: 61ce46d7-c218-409f-9560-7ccd8bfda25d
        userCondition: null
group: null
groupChildBlockTypes: true
handle: embedCode
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Embed Code'
topLevel: true
