childBlocks: null
conditions: null
description: ''
enabled: true
field: aefea3fc-ff45-4615-b305-9079e2cc6c44 # Page Builder: Impact Report
fieldLayouts:
  9650b82f-3a58-4287-96fb-a220b900aab0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7f134341-6c01-4975-9ea9-60df3c3dd5f0 # Image
            instructions: null
            label: 'Factoid Graphic'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0a04da40-eba0-4769-a30f-db0bd9a15141
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 4f1a3081-cb03-47eb-b862-638e1b362e22 # Image Position [L|R]
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3dc78129-153e-4c59-88e3-2409dbdfdd0b
            userCondition: null
            warning: null
            width: 25
        name: Images
        uid: f070907d-bd28-41de-8452-eea16ad3be83
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d24ab695-25c2-4078-b7e4-b936aa667ac6 # Pre-Eyebrow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e52bb9ad-2afd-4802-b68b-8ef9fee25852
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e39974bd-ec97-4187-be91-a431e1a4fbd7 # Eyebrow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3e8ae80c-2141-4698-bfe0-09323ae7dfa0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6ab970bd-1621-4c3f-8eeb-6887ac8cbb2c # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 75b3cd77-5b72-452e-8b1a-5248a8fdb356
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f700d39b-3a4f-4c99-a961-d9fb1f3df887 # Subheading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7f03266-1236-4c6f-bf12-ee981888edcb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d4a66aad-fd77-4abe-97e2-a01cabc77bac # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1d6bd80d-1422-4aa4-a9bd-b93b3a12ec69
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8d53efd7-98eb-40ec-a000-4b904766072d # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ac8dcda1-47f0-42cf-b4c6-f31d87c05914
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 0014573b-36a9-48c6-b523-64fbabf469f2 # Button Style
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1e2b9f66-d7b3-4482-b70f-948cd3058120
            userCondition: null
            warning: null
            width: 25
        name: Description
        uid: 8240c104-840d-4b7c-8dbb-febb1932f32a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 28a04878-3d6a-4889-ad36-87cce2dd449e # Padding: Top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2a8644b8-0e04-4dc6-88a1-d2091a67aedd
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 040d7db9-375b-4b41-989d-2e38c47b90f6 # Padding: Bottom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6e2ed124-2a28-4b0b-9797-fc0a6ac86457
            userCondition: null
            warning: null
            width: 25
        name: 'Section Settings'
        uid: 192639f5-faa3-4750-9c07-d3b420e9995f
        userCondition: null
group: null
groupChildBlockTypes: true
handle: factoid
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Factoid
topLevel: true
