childBlocks: null
conditions: null
description: ''
enabled: true
field: f69cfc32-4011-4eea-a32a-f5ae9fd5b24e # Page Builder: General
fieldLayouts:
  940ff963-8627-4f9a-9637-b4c9399292a4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a8366a49-97a6-4a33-a567-a948f6a481ac # Section ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8de6c5be-515b-4bfb-a6fa-5c994d0300ef
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: aa3d7fc1-1a22-4fff-8fe2-28dd1ab8388e # Pre-heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d2737300-c35c-4c5b-b791-2b20f22eca22
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 31f2b911-731f-42b5-84c6-4b2777260f2f # Section Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 22472940-db86-4445-953b-923593c4797b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d4a66aad-fd77-4abe-97e2-a01cabc77bac # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a4f21d6c-84a6-405c-9d71-22cb4d3e9808
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: be950c11-5fd5-43e5-962d-aa30d3dd2834 # Form
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9d3b2a4c-df67-48d5-8dd7-b6a456ff49b6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: bc5dec6e-b156-49e9-99e9-6c3b8a607475
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: dfbc0047-f74f-4940-baf3-7f9402fc918e # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6e3b41b9-76e6-4b78-b06d-1e139454e89a
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 28a04878-3d6a-4889-ad36-87cce2dd449e # Padding: Top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 86e6830f-7673-4947-931a-81ad05d29dea
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 040d7db9-375b-4b41-989d-2e38c47b90f6 # Padding: Bottom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9bada41e-2fca-46e7-923a-dd7acd274c20
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 12a86971-9af3-496d-9a73-1f277506afaa # Padding: Sides
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7ac8ddc4-702e-4626-a1ee-2c94ba23f6ac
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 55f89f73-30c8-4eeb-b491-a0da78da6657 # Text Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c6aa2425-eeae-453e-ade5-699897c80cb6
            userCondition: null
            warning: null
            width: 25
        name: 'Section Settings'
        uid: 5f91971b-8863-4f41-b600-7ead5aceab15
        userCondition: null
group: 2734260c-14b6-412b-a372-5a4ee016497a # Media
groupChildBlockTypes: true
handle: form
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Form
topLevel: true
