childBlocks: null
conditions: null
description: ''
enabled: true
field: 0914ee96-13fc-4737-ae93-8ab00d611b35 # Page Builder: Blog
fieldLayouts:
  ae502cc1-372c-4b17-9f33-c27f2d3e11eb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: aa3d7fc1-1a22-4fff-8fe2-28dd1ab8388e # Pre-heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d1069a3-b0e2-4c41-a3d5-72bc5d6e3aa2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 31f2b911-731f-42b5-84c6-4b2777260f2f # Section Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 325c37fd-5256-4c0d-966b-05c3c5c8987e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 51fc1db6-6668-4f93-91d3-ec12bfba9cef
            userCondition: null
          -
            elementCondition: null
            fieldUid: ce130366-bd6b-46be-ad59-10108ee88718 # Image: Desktop
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d27d3b9d-e5d7-4258-8773-419acded6d24
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: b99b6148-253d-4660-ac78-eaf2703b3856 # Image: Mobile
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b7de8d3e-303d-445f-8af9-1f5d2536734d
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: decf4c9d-4084-42d5-b054-7c034dcebcd2 # Grid Width
            instructions: null
            label: 'Image Width'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3dcb193d-1071-4395-82b7-b8956222143b
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 4f1a3081-cb03-47eb-b862-638e1b362e22 # Image Position [L|R]
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3411e976-21cf-4f09-8c17-6912c652b702
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 06c521fb-c681-49ba-8fe6-f6d08a21dbee
            userCondition: null
          -
            elementCondition: null
            fieldUid: d4a66aad-fd77-4abe-97e2-a01cabc77bac # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 72b79df9-f871-4f76-a885-2f5904b141a3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8d53efd7-98eb-40ec-a000-4b904766072d # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 169fa72e-b8a1-4406-af3b-9341fde5d41e
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 0014573b-36a9-48c6-b523-64fbabf469f2 # Button Style
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 964a1719-e67e-4e65-8cd2-29d0d805e133
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 28dd7732-9eb2-4110-903e-256aebcf25fb
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: dfbc0047-f74f-4940-baf3-7f9402fc918e # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: af7ffd71-7885-4dda-9026-7980b7ec75e8
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 28a04878-3d6a-4889-ad36-87cce2dd449e # Padding: Top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 668a4d71-ab6f-4020-903f-67aac11bad79
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 040d7db9-375b-4b41-989d-2e38c47b90f6 # Padding: Bottom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 400a4dab-53c0-490d-9dd5-d34ddfc225c5
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 55f89f73-30c8-4eeb-b491-a0da78da6657 # Text Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e27aaa39-b6c4-4a80-aded-5bd6892c4ee6
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: fb633af9-99e4-499c-b90f-60a8039f3046 # Text Alignment
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 906b9ebb-7d44-4026-8bb6-702ee6438cd5
            userCondition: null
            warning: null
            width: 25
        name: 'Section Settings'
        uid: f6d0c382-470c-418a-b25d-9a39b30e2f47
        userCondition: null
group: null
groupChildBlockTypes: true
handle: general
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: General
topLevel: true
