childBlocks: null
conditions: null
description: ''
enabled: true
field: 0914ee96-13fc-4737-ae93-8ab00d611b35 # Page Builder: Blog
fieldLayouts:
  ea30019e-97f4-440c-9910-0388a3fd9a18:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d24ab695-25c2-4078-b7e4-b936aa667ac6 # Pre-Eyebrow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5d2fdd97-5bfd-4291-9595-29f6e52608ab
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e39974bd-ec97-4187-be91-a431e1a4fbd7 # Eyebrow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 98add605-00b9-472b-836f-4701acf6f7a6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 31f2b911-731f-42b5-84c6-4b2777260f2f # Section Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bed9e134-a9a0-442b-b56d-47b62917ed59
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d4a66aad-fd77-4abe-97e2-a01cabc77bac # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 962dc24f-d384-4ae5-bea2-836e18d02242
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6add601c-de5e-4e85-8618-137007c0f910 # Signatures
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 94ba6c40-b2c8-4c0a-8794-a6e1ec1f454c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8d53efd7-98eb-40ec-a000-4b904766072d # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9304f78e-7795-427f-890c-1be52a1aee1d
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 0014573b-36a9-48c6-b523-64fbabf469f2 # Button Style
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 86727f82-6d3f-482d-82c4-50263bfb4d92
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 06913910-3e30-4eba-9586-b1e0f1ba1a40
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: dfbc0047-f74f-4940-baf3-7f9402fc918e # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 858f6e54-17f7-4545-9b0d-c6ad4894158b
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 28a04878-3d6a-4889-ad36-87cce2dd449e # Padding: Top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: faed5e3c-3efc-444f-88b1-324eb6a39b44
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 040d7db9-375b-4b41-989d-2e38c47b90f6 # Padding: Bottom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3f8f341d-c1f8-449f-b3ee-96f0558918c8
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: fb633af9-99e4-499c-b90f-60a8039f3046 # Text Alignment
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bf45dd5a-9744-4b4b-9894-f02ec9134e1d
            userCondition: null
            warning: null
            width: 25
        name: 'Section Settings'
        uid: 41f569ce-cb0c-47d0-9ffe-7b37fbaa42d2
        userCondition: null
group: null
groupChildBlockTypes: true
handle: generalLargeText
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'General: Large Text'
topLevel: true
