childBlocks: null
conditions: null
description: ''
enabled: true
field: 23354ff5-9e58-4f25-a8b1-77c6f7b7b7d8 # Page Header
fieldLayouts:
  5fdd85e3-e005-4510-935a-5b9c6d5b2e1f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'Insert one large tile and two small tiles. The large tile will be shown first.'
            type: craft\fieldlayoutelements\Tip
            uid: d344734f-df68-400e-8cc0-0f23ab6e39ff
            userCondition: null
          -
            elementCondition: null
            fieldUid: 0990fff1-3f3d-49e5-a5b1-afdeb683d20e # CTA Tile: Large
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d39da52b-80e8-4362-9bbf-c246bbb7450a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e11568a1-11e3-4147-ae18-1ff01fdcd4f7 # CTA Tile: Small
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eec20f99-30c7-46cd-8f76-c8e969985eb8
            userCondition: null
            warning: null
            width: 100
        name: Tiles
        uid: fe2972c4-1e18-41ef-9fa5-a306ac7674cb
        userCondition: null
group: null
groupChildBlockTypes: true
handle: largeSmallSmall
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Large | Small | Small'
topLevel: false
