childBlocks:
  - podcastTile
conditions: null
description: ''
enabled: true
field: aefea3fc-ff45-4615-b305-9079e2cc6c44 # Page Builder: Impact Report
fieldLayouts:
  854d10a4-601f-444d-a92f-03a80f54e0ae:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 76c2555a-23b9-4d53-8c79-13892f75b970 # Factoid Description Box
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1ed98aa4-d898-434a-9d57-2cb610797594
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4f1a3081-cb03-47eb-b862-638e1b362e22 # Image Position [L|R]
            instructions: null
            label: 'Factoid Position [L|R]'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bad04af4-da3e-48d3-9b5c-8936b38cfc05
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 524c6e05-4d16-4e49-86a1-edfb5ff0e70c # Animation Settings
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e3b980f1-bcd4-4a1c-8e51-a60aca058a97
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: benf\neo\fieldlayoutelements\ChildBlocksUiElement
            uid: cf19c2d0-c59a-4295-a460-59fa072c02dc
            userCondition: null
          -
            elementCondition: null
            fieldUid: 8d53efd7-98eb-40ec-a000-4b904766072d # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5b7095ff-ac55-4565-823c-208657a98f20
            userCondition: null
            warning: null
            width: 100
        name: Factoid
        uid: 39401142-a2e7-4e48-a5ec-74345850353c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d24ab695-25c2-4078-b7e4-b936aa667ac6 # Pre-Eyebrow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 72358b30-98b2-4831-bba9-6916b29491e4
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: fb633af9-99e4-499c-b90f-60a8039f3046 # Text Alignment
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2e2cc323-623a-4699-9bf0-a92739c8132e
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: e39974bd-ec97-4187-be91-a431e1a4fbd7 # Eyebrow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c63b9716-e130-482b-b6f7-02969e8f6fab
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7f134341-6c01-4975-9ea9-60df3c3dd5f0 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed313f74-8976-4aab-a391-cf3edfcc068b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6ab970bd-1621-4c3f-8eeb-6887ac8cbb2c # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 892b62f6-07f1-4ed6-9f84-e8037c0db02a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d4a66aad-fd77-4abe-97e2-a01cabc77bac # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 196b2c52-fef2-4f49-8d0f-00620e33e228
            userCondition: null
            warning: null
            width: 100
        name: Description
        uid: 32268a8d-12a2-4eff-b06b-2bc00abd5883
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 28a04878-3d6a-4889-ad36-87cce2dd449e # Padding: Top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f33386f6-db6e-4635-a425-dae3fc696479
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 040d7db9-375b-4b41-989d-2e38c47b90f6 # Padding: Bottom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0675b708-c258-4263-9821-3c64a3f11cc7
            userCondition: null
            warning: null
            width: 25
        name: 'Section Settings'
        uid: c1a37d30-cc56-42b3-8c82-da3b6d0b97a1
        userCondition: null
group: null
groupChildBlockTypes: true
handle: podcastBlock
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Podcast Block'
topLevel: true
