childBlocks:
  - previewCard
conditions: null
description: ''
enabled: true
field: f69cfc32-4011-4eea-a32a-f5ae9fd5b24e
fieldLayouts:
  5f6838e6-51b0-4bf0-8402-89f415fde811:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a8366a49-97a6-4a33-a567-a948f6a481ac
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c93fb777-e9f0-4f9d-866b-ce694b4a1c30
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: aa3d7fc1-1a22-4fff-8fe2-28dd1ab8388e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7b3b8b4d-eebf-4a71-85be-a82cb82bfd36
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 31f2b911-731f-42b5-84c6-4b2777260f2f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a495fe71-c87d-4b56-9ce6-92d64cac5c1f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d4a66aad-fd77-4abe-97e2-a01cabc77bac
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fe288b02-8d73-4fe2-a9f8-348d3c4c9b82
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e636fe1a-91ea-493b-81c8-354c9c08220f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2268a356-41a2-41db-af5f-6f45bc251103
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: benf\neo\fieldlayoutelements\ChildBlocksUiElement
            uid: 2d8e9bba-28ca-4a26-a8d1-f305e4f1400e
            userCondition: null
        name: Content
        uid: 243effad-4f91-43bf-b60f-334e2cccee3f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: dfbc0047-f74f-4940-baf3-7f9402fc918e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 54b37dfd-045f-46dc-9efe-36d93071d259
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 28a04878-3d6a-4889-ad36-87cce2dd449e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d09d6c26-afce-4a0f-8aa8-91829991efa3
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 040d7db9-375b-4b41-989d-2e38c47b90f6
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 195ecbfd-cf84-45e7-afb3-074ca1676ebf
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 12a86971-9af3-496d-9a73-1f277506afaa
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed0469c3-9b09-461d-b066-7365e52ad986
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 55f89f73-30c8-4eeb-b491-a0da78da6657
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7709ba6b-b574-4a2a-a1c2-eabe29109356
            userCondition: null
            warning: null
            width: 25
        name: 'Section Settings'
        uid: 145d5f2a-7b6f-4db6-a495-e6de73ba97fd
        userCondition: null
group: null
groupChildBlockTypes: true
handle: previewCards
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Preview Cards'
topLevel: true
