childBlocks: null
conditions: null
description: ''
enabled: true
field: f69cfc32-4011-4eea-a32a-f5ae9fd5b24e # Page Builder: General
fieldLayouts:
  9dcc4a48-848d-4e69-8780-8c88be7c841b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a8366a49-97a6-4a33-a567-a948f6a481ac # Section ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 890b9557-825a-4e00-a3ba-2dfa836e79e6
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: aa3d7fc1-1a22-4fff-8fe2-28dd1ab8388e # Pre-heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f99e2891-997e-4a51-8a49-96fc8b329870
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 31f2b911-731f-42b5-84c6-4b2777260f2f # Section Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2a38894d-a86b-4efc-8efa-07aec89d8b2e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d4a66aad-fd77-4abe-97e2-a01cabc77bac # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6eb36cb5-7a3f-4614-a218-9aaf37c272b5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: da39494d-b4b7-4e57-8c52-887a18f71959 # Resource Cards
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 24c7689b-df02-46b2-943e-df5276fffb9c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: b15a50b0-8595-40a6-b214-9ea5cba23fb4
            userCondition: null
          -
            elementCondition: null
            fieldUid: c01f8239-e66d-46b2-92be-458a8a5914f6 # Resources
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6ee3a562-2234-4cde-a5d4-a0d8acaf7730
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 57577486-c86a-4440-a46d-29c9c3811fb2
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: dfbc0047-f74f-4940-baf3-7f9402fc918e # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f78a5ee8-1517-40fb-9d98-0a414407720f
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 28a04878-3d6a-4889-ad36-87cce2dd449e # Padding: Top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fe6d0144-d1ee-416f-bfa9-d5cbc53b56b3
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 040d7db9-375b-4b41-989d-2e38c47b90f6 # Padding: Bottom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ce81133-30ae-4dcd-aadb-5193833cbe63
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 12a86971-9af3-496d-9a73-1f277506afaa # Padding: Sides
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e7345e8a-0f21-4983-b69d-afa61caf2e80
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 55f89f73-30c8-4eeb-b491-a0da78da6657 # Text Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b9b1d716-f0a7-40ed-9e26-1b713080fab6
            userCondition: null
            warning: null
            width: 25
        name: 'Section Settings'
        uid: 3083175e-52e2-499b-9e63-06f3165cca9c
        userCondition: null
group: 89a66249-b68c-4d46-81b7-9ef3dac29401 # Cards
groupChildBlockTypes: true
handle: resourceCards
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Resource Cards'
topLevel: true
