childBlocks:
  - gutterFigure
conditions: null
description: ''
enabled: true
field: 0914ee96-13fc-4737-ae93-8ab00d611b35 # Page Builder: Blog
fieldLayouts:
  c3fae260-4b16-46d0-84ef-bc7162083803:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            type: benf\neo\fieldlayoutelements\ChildBlocksUiElement
            uid: f395f244-0939-41fb-86f5-d2c185f08131
            userCondition: null
        name: Content
        uid: a93b5071-39c8-49c2-b677-12583e63ba1a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 28a04878-3d6a-4889-ad36-87cce2dd449e # Padding: Top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 22223ee4-0041-4ec2-8d32-b49eb7415839
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 040d7db9-375b-4b41-989d-2e38c47b90f6 # Padding: Bottom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 472af434-0892-45b9-9de2-88dc783dfd2b
            userCondition: null
            warning: null
            width: 100
        name: 'Section Settings'
        uid: 3c5fa4bf-c2dc-4eed-9af0-96205724b653
        userCondition: null
group: null
groupChildBlockTypes: true
handle: textFiguresInGutter
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Text+Figures in Gutter'
topLevel: true
