defaultPlacement: end
enableVersioning: true
handle: pages
name: Pages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5cf2d429-9442-49de-b0fb-aaaec557b2cd: # TMF
    enabledByDefault: true
    hasUrls: true
    template: _sections/pages.twig
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: f27f2ef8-82a4-4195-af45-6fa34b33442d
type: structure
