childBlocks: null
color: null
conditions: null
description: ''
enabled: true
entryType: null
field: f69cfc32-4011-4eea-a32a-f5ae9fd5b24e # Page Builder: General
fieldLayouts:
  dcba9f9c-11b2-4891-a510-1eb59c592d66:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: aa3d7fc1-1a22-4fff-8fe2-28dd1ab8388e # Pre-heading
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 61b86704-4a4b-43cd-81e9-26a2c1f5b82a
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 55f89f73-30c8-4eeb-b491-a0da78da6657 # Text Color
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f9be4791-3c4b-4d73-9e2b-88a4ef9a1f94
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6ab970bd-1621-4c3f-8eeb-6887ac8cbb2c # Heading
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 51a3171d-8626-4a0a-8536-20c193d42172
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: d4a66aad-fd77-4abe-97e2-a01cabc77bac # Description
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f3051144-956a-4941-a6ed-25fccc53733d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 8d53efd7-98eb-40ec-a000-4b904766072d # Button
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 90c26d01-76ab-48c7-a05e-5584be4371f2
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e47176e3-add5-4f79-a2e5-6544b4099f0f # Download
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 983dd573-866c-441d-b49f-5529492ef5d5
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: fb633af9-99e4-499c-b90f-60a8039f3046 # Text Alignment
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1db8ebd4-4ceb-4a7a-a091-43bf42ac16da
            userCondition: null
            warning: null
            width: 100
        name: Column
        uid: f57ade60-b9e8-42c3-8717-a9725295c890
        userCondition: null
    thumbFieldKey: null
group: cfcf5277-7782-4698-bf84-73607da709a9 # Text Blocks
groupChildBlockTypes: true
handle: columnText
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Column: Text'
topLevel: false
