childBlocks:
  - equalSizeTiles
conditions: null
description: ''
enabled: true
field: aefea3fc-ff45-4615-b305-9079e2cc6c44 # Page Builder: Impact Report
fieldLayouts:
  ac552481-28d5-454b-aacc-57f5ddcb3d43:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a8366a49-97a6-4a33-a567-a948f6a481ac # Section ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f6de3a1-9e13-4f3e-88c4-89d40611547a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: benf\neo\fieldlayoutelements\ChildBlocksUiElement
            uid: 58dc1a68-4082-4cb1-ad89-c2dd50e1dd6a
            userCondition: null
        name: Content
        uid: 416f88bb-3ceb-4d1f-88ad-c72f32adee71
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 28a04878-3d6a-4889-ad36-87cce2dd449e # Padding: Top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b0d6b2f1-6d1c-4b82-a5a6-ed55838e22d5
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 040d7db9-375b-4b41-989d-2e38c47b90f6 # Padding: Bottom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 59f2302b-1ec9-445a-a02b-8c06a0fca6a9
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 12a86971-9af3-496d-9a73-1f277506afaa # Padding: Sides
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 23562204-1a1f-4e5e-bd01-afd2a561edab
            userCondition: null
            warning: null
            width: 25
        name: 'Section Settings'
        uid: bb2ccc09-186b-46f2-b3fa-669ee6395b10
        userCondition: null
group: null
groupChildBlockTypes: true
handle: ctaTiles
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'CTA Tiles'
topLevel: true
