childBlocks: null
conditions: null
description: ''
enabled: true
field: f69cfc32-4011-4eea-a32a-f5ae9fd5b24e # Page Builder: General
fieldLayouts:
  2bcbe99f-dce9-4642-8102-85ef4de00caf:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a8366a49-97a6-4a33-a567-a948f6a481ac # Section ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b193f669-d3b7-4658-872e-5238b85c83e9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 479ec005-6f3d-4922-b8e5-da10aad75bdc # Data Tables
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ba49148e-1e31-497a-b71d-95222b40c60d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cdb162a5-f0d2-429b-b5ac-588fc77a48da # Summary
            instructions: null
            label: Footnotes
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c825e164-ce28-49ce-9828-6f7617f154c0
            userCondition: null
            warning: null
            width: 100
        name: Tables
        uid: 1963b42a-e53a-4f12-92ad-e2660ec972eb
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: dfbc0047-f74f-4940-baf3-7f9402fc918e # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e3cf2e9e-e731-41ec-8340-5019902e0309
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 28a04878-3d6a-4889-ad36-87cce2dd449e # Padding: Top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7fd17a6f-2cf0-45a0-8e8e-fb6869a01d6f
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 040d7db9-375b-4b41-989d-2e38c47b90f6 # Padding: Bottom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8184ef13-1449-4066-a93a-c6b5c7d2ead9
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 12a86971-9af3-496d-9a73-1f277506afaa # Padding: Sides
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 93da294e-187b-474e-8cf5-a55bdcb14ca8
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 55f89f73-30c8-4eeb-b491-a0da78da6657 # Text Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0b1f5987-6924-4321-b154-a9e4e28f987a
            userCondition: null
            warning: null
            width: 25
        name: 'Section Settings'
        uid: 78a4b31f-a392-442a-bdab-819be60eee55
        userCondition: null
group: cfcf5277-7782-4698-bf84-73607da709a9
groupChildBlockTypes: true
handle: dataTableFullWidth
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Data Table: Full Width'
topLevel: true
