childBlocks: null
color: null
conditions: null
description: ''
enabled: true
entryType: null
field: aefea3fc-ff45-4615-b305-9079e2cc6c44 # Page Builder: Impact Report
fieldLayouts:
  52ba90fb-e459-4ed2-902a-d512724055aa:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f06a4480-f195-4705-bd40-a33a08e72d0f # Images
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cab1f855-f0af-4214-a80c-1f9e24de5b1e
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 48fda275-cc4f-48a3-9d79-c38f9cd4d1d6 # Factoid Layout
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4ceb1a8c-d870-4369-9fcf-3c86aea69548
            userCondition: null
            warning: null
            width: 25
        name: Graphics
        uid: cdf996f5-f0e4-4302-884f-2d73da4c9898
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 524c6e05-4d16-4e49-86a1-edfb5ff0e70c # Animation Settings
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a3e8aeee-e2f5-4685-a637-3126437db6b0
            userCondition: null
            warning: null
            width: 100
        name: Animation
        uid: 6878d2af-1e1b-49b5-a71a-d6eff4c39ac3
        userCondition: null
    thumbFieldKey: null
group: null
groupChildBlockTypes: true
handle: factoid2Up
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Factoid: 2-Up'
topLevel: false
