childBlocks: null
color: null
conditions: null
description: ''
enabled: true
entryType: null
field: 0914ee96-13fc-4737-ae93-8ab00d611b35 # Page Builder: Blog
fieldLayouts:
  ac750f5b-8d72-4224-933b-af5383f87ba6:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7f134341-6c01-4975-9ea9-60df3c3dd5f0 # Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 14590273-5cd8-4bff-b197-cd9f0b13199d
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a92a5281-32dc-4a23-ace9-8c14c8ec62ac # Position[L|C|R]
            handle: null
            instructions: null
            label: 'Image: Position'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 960c2d91-01d0-4e68-87bf-5f0ede13583b
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 9ff86f39-6873-42df-883a-5d1692acebbc # Text Size
            handle: null
            instructions: null
            label: 'Image: Size'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b361ebf2-5afd-4c50-a3b5-af9239e5e2c5
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: cec407c4-ded3-4457-9ffd-7caf96ab0281 # Caption
            handle: null
            instructions: null
            label: 'Image: Caption'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 491650e4-9102-43b9-9c12-e7b78563808c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: d4a66aad-fd77-4abe-97e2-a01cabc77bac # Description
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 90c62e05-0e7a-4b70-a38b-62dd917e54a3
            userCondition: null
            warning: null
            width: 100
        name: 'Content Block'
        uid: 7f4b3f66-238e-4ceb-a6e3-10364ad69813
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 28a04878-3d6a-4889-ad36-87cce2dd449e # Padding: Top
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cc13d0db-7b34-4095-9617-0a74683b91d8
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 040d7db9-375b-4b41-989d-2e38c47b90f6 # Padding: Bottom
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a37fe10-8d5a-47ed-a0a3-971b17a9f003
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 55f89f73-30c8-4eeb-b491-a0da78da6657 # Text Color
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 88d7950d-7e1a-41f9-84aa-c02bc00f9c25
            userCondition: null
            warning: null
            width: 25
        name: 'Block Spacing'
        uid: 62626b8c-fe7d-4fb8-a85b-270b410aaf29
        userCondition: null
    thumbFieldKey: null
group: null
groupChildBlockTypes: true
handle: gutterFigure
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Gutter Figure'
topLevel: false
