childBlocks:
  - imageCard
conditions: null
description: ''
enabled: true
field: f69cfc32-4011-4eea-a32a-f5ae9fd5b24e # Page Builder: General
fieldLayouts:
  8c2178f5-cc1e-47fd-952d-9fb8c358f72c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            type: benf\neo\fieldlayoutelements\ChildBlocksUiElement
            uid: 71cb0c87-49d0-49c0-a4a9-0f508520bffd
            userCondition: null
        name: Content
        uid: 2f368fdc-4e41-4d1f-9e5f-4c9344293665
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: dfbc0047-f74f-4940-baf3-7f9402fc918e # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 66bd4b96-8b7f-4c5e-bdf5-f03021cac365
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 28a04878-3d6a-4889-ad36-87cce2dd449e # Padding: Top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 79bc028e-9332-41c4-ab46-75967d9a566c
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 040d7db9-375b-4b41-989d-2e38c47b90f6 # Padding: Bottom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0f752f61-9092-40d7-b54f-7911e6b16714
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 12a86971-9af3-496d-9a73-1f277506afaa # Padding: Sides
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e2cb49c6-da79-488c-9849-2bcc44a53b4f
            userCondition: null
            warning: null
            width: 25
        name: 'Section Settings'
        uid: 34390d15-b0ba-4718-aa1e-5d6154e73cff
        userCondition: null
group: 89a66249-b68c-4d46-81b7-9ef3dac29401
groupChildBlockTypes: true
handle: imageCards
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Image Cards'
topLevel: true
