childBlocks: null
conditions: null
description: ''
enabled: true
field: f69cfc32-4011-4eea-a32a-f5ae9fd5b24e # Page Builder: General
fieldLayouts:
  b71904f9-2af8-4357-b1ed-3daf9ee87fec:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a8366a49-97a6-4a33-a567-a948f6a481ac # Section ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 77def6ae-b174-48f2-8bf2-0c6f3df57ec1
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: ce130366-bd6b-46be-ad59-10108ee88718 # Image: Desktop
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 578a7836-6495-4def-96c8-c307279b3a1c
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: b99b6148-253d-4660-ac78-eaf2703b3856 # Image: Mobile
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 52c9ffa7-e693-40c7-8ab0-2f8b5123a223
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 4f1a3081-cb03-47eb-b862-638e1b362e22 # Image Position [L|R]
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f9e00a30-1c5f-4248-a0cd-9c0de740c48d
            userCondition: null
            warning: null
            width: 25
        name: Image
        uid: e25e0b6b-f2e6-4c9d-bfeb-025a293a2da3
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: aa3d7fc1-1a22-4fff-8fe2-28dd1ab8388e # Pre-heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bc40c9a1-d92e-4b35-b461-ef431221f211
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 31f2b911-731f-42b5-84c6-4b2777260f2f # Section Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1771e249-1b1a-4c39-a27d-2485c4d251a4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d4a66aad-fd77-4abe-97e2-a01cabc77bac # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d5a6bc8c-da9c-4103-90c3-689a1963c8e7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 17fcc0b6-4e93-425f-9380-11c07300553d # Buttons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ddc2056f-ea86-4673-8b32-c248975e7b39
            userCondition: null
            warning: null
            width: 100
        name: 'Text Description'
        uid: b38cec44-eda0-4e82-97b0-ecfff23cc297
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: dfbc0047-f74f-4940-baf3-7f9402fc918e # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0658cb22-e461-4adf-8b81-cffca5b6d167
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 28a04878-3d6a-4889-ad36-87cce2dd449e # Padding: Top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dcf589e9-0eac-4e17-a402-6b35109b30c9
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 040d7db9-375b-4b41-989d-2e38c47b90f6 # Padding: Bottom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b37ef18e-b985-4d99-a755-aaef8a5f3369
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 55f89f73-30c8-4eeb-b491-a0da78da6657 # Text Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ac52ddda-a2e4-41c9-83b5-50edfb198cd1
            userCondition: null
            warning: null
            width: 25
        name: 'Section Settings'
        uid: 75688b27-0354-4a03-a054-32e9eb5a7e1b
        userCondition: null
group: cfcf5277-7782-4698-bf84-73607da709a9
groupChildBlockTypes: true
handle: imgTextBlock
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Img+Text Block'
topLevel: true
