childBlocks: null
color: null
conditions: null
description: ''
enabled: true
entryType: null
field: f69cfc32-4011-4eea-a32a-f5ae9fd5b24e # Page Builder: General
fieldLayouts:
  e09eda3c-18ba-4f21-88de-dc1c173dc2ef:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a8366a49-97a6-4a33-a567-a948f6a481ac # Section ID
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 58126fd6-5b1e-4b23-b6a6-4392737dd0e3
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: aa3d7fc1-1a22-4fff-8fe2-28dd1ab8388e # Pre-heading
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 78301439-d29a-4d8b-9f40-af344527afdf
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 31f2b911-731f-42b5-84c6-4b2777260f2f # Section Heading
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f86f1e42-1542-4915-b9b2-f669f80db270
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: d4a66aad-fd77-4abe-97e2-a01cabc77bac # Description
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c2706c7b-3bae-43cf-9145-04b0e7463c1f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 17fcc0b6-4e93-425f-9380-11c07300553d # Buttons
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e9447807-09b5-4f91-b6d7-02ed4dc07b7f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d13f991a-3322-4794-a0dd-ebad276bf5f8
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: dfbc0047-f74f-4940-baf3-7f9402fc918e # Background Color
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1e49b2f1-ce36-4a9b-854c-c3f5dc6b0032
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 28a04878-3d6a-4889-ad36-87cce2dd449e # Padding: Top
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 500b079f-2421-4faf-b04b-9faddd4923f8
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 040d7db9-375b-4b41-989d-2e38c47b90f6 # Padding: Bottom
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2cde2fdb-6f94-491d-a07a-bb2687557d12
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: fb633af9-99e4-499c-b90f-60a8039f3046 # Text Alignment
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b28f53c8-ed85-49cc-ad7e-d83fbd0ee13d
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 55f89f73-30c8-4eeb-b491-a0da78da6657 # Text Color
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0638e750-a117-4f40-ac02-82879a476ab8
            userCondition: null
            warning: null
            width: 25
        name: 'Section Settings'
        uid: 193ceb77-cb82-467f-870d-93aefe5b8f67
        userCondition: null
    thumbFieldKey: null
group: cfcf5277-7782-4698-bf84-73607da709a9 # Text Blocks
groupChildBlockTypes: true
handle: leadBlock
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Lead Block'
topLevel: true
