childBlocks: null
color: null
conditions: null
description: ''
enabled: true
entryType: null
field: f69cfc32-4011-4eea-a32a-f5ae9fd5b24e # Page Builder: General
fieldLayouts:
  fc9bc523-5937-4cd8-9cb8-d7155c2d6d3f:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a8366a49-97a6-4a33-a567-a948f6a481ac # Section ID
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 782eaa34-d4c2-42ab-9b81-f1bd57753e6b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 865ca38f-50ad-4e67-9a95-bd05ae709908 # Embed Code
            handle: null
            instructions: null
            label: 'Formstack Embed Code'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0a014fa-488b-4fc1-b27c-ac3304083be0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2f4c93da-c41d-414a-9b6f-d8fa038d754f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: dfbc0047-f74f-4940-baf3-7f9402fc918e # Background Color
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f2473632-a6a9-474e-a47b-0bf988857906
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 28a04878-3d6a-4889-ad36-87cce2dd449e # Padding: Top
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 90c49207-1e0a-4bc9-95bc-7a1d36b9a464
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 040d7db9-375b-4b41-989d-2e38c47b90f6 # Padding: Bottom
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3d6844d1-0bec-44fc-80e0-b902d5909b4e
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 12a86971-9af3-496d-9a73-1f277506afaa # Padding: Sides
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ff6b5cec-6b41-401a-a5f2-2656eaf41d48
            userCondition: null
            warning: null
            width: 25
        name: 'Section Settings'
        uid: 51485c50-6857-4d3b-9024-26d3d08ef49f
        userCondition: null
    thumbFieldKey: null
group: 2734260c-14b6-412b-a372-5a4ee016497a # Media
groupChildBlockTypes: true
handle: mailchimpOptinValidator
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Mailchimp Opt-In Validator'
topLevel: true
