childBlocks: null
color: null
conditions: null
description: ''
enabled: true
entryType: null
field: f69cfc32-4011-4eea-a32a-f5ae9fd5b24e # Page Builder: General
fieldLayouts:
  9fccd976-a85a-43c2-b4bc-e9232075513f:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7f134341-6c01-4975-9ea9-60df3c3dd5f0 # Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd7ab92b-6e8b-4eef-a055-1b4990ca2eb7
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 55f89f73-30c8-4eeb-b491-a0da78da6657 # Text Color
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9bded225-01fa-4878-a557-ce171dc91e3f
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: aa3d7fc1-1a22-4fff-8fe2-28dd1ab8388e # Pre-heading
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4659dd57-375e-4213-8827-7603c381c2a6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6ab970bd-1621-4c3f-8eeb-6887ac8cbb2c # Heading
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec8a62fd-c079-44a5-8fb0-ae8f5872c5e5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: cdb162a5-f0d2-429b-b5ac-588fc77a48da # Summary
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d7a360f7-946e-406b-bf86-b8fc959217d3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 8d53efd7-98eb-40ec-a000-4b904766072d # Button
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3ba7ae70-7b6f-4b8e-b59e-f1aaa6329588
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e47176e3-add5-4f79-a2e5-6544b4099f0f # Download
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9b94b8a3-9a34-443c-991d-27aaf0b8775b
            userCondition: null
            warning: null
            width: 25
        name: Card
        uid: d8484d62-7f21-46a3-aeec-7d8ba55f8f92
        userCondition: null
    thumbFieldKey: null
group: 89a66249-b68c-4d46-81b7-9ef3dac29401 # Cards
groupChildBlockTypes: true
handle: previewCard
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Preview Card'
topLevel: false
