childBlocks:
  - button
color: null
conditions: null
description: ''
enabled: true
entryType: null
field: 0914ee96-13fc-4737-ae93-8ab00d611b35 # Page Builder: Blog
fieldLayouts:
  72dec036-a682-483b-b2df-dd497d0fc4ce:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: d24ab695-25c2-4078-b7e4-b936aa667ac6 # Pre-Eyebrow
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a841dddf-6e8a-4366-892b-d7527cde3093
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: aa3d7fc1-1a22-4fff-8fe2-28dd1ab8388e # Pre-heading
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1fc76d04-8f60-49d0-80b3-40b400de930e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6ab970bd-1621-4c3f-8eeb-6887ac8cbb2c # Heading
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f9a106a9-694e-45ce-aca7-556116c09ebf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f700d39b-3a4f-4c99-a961-d9fb1f3df887 # Subheading
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c5077f3-d45e-4564-8d5c-8cbaa910ab68
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: d4a66aad-fd77-4abe-97e2-a01cabc77bac # Description
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 88b6ec31-9ea3-4a18-8cec-384fed47d75c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            elementCondition: null
            type: benf\neo\fieldlayoutelements\ChildBlocksUiElement
            uid: 5ea5ea58-a56a-4fea-946c-8c0bd8280936
            userCondition: null
        name: Text
        uid: 6f67e8a7-2aa9-494a-abde-1ece29f64783
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: ce130366-bd6b-46be-ad59-10108ee88718 # Image: Desktop
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b4d35aad-49dc-44ce-9fa6-5a51e0fe3e01
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: b99b6148-253d-4660-ac78-eaf2703b3856 # Image: Mobile
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 43486960-d90d-432d-91a0-e499e0e6b6fe
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 2f76bca5-2eaf-4262-8c5d-edb7401cc84f # Video
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 63ba0939-d9a3-4c8c-9abc-da8f18a120ac
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 4f1a3081-cb03-47eb-b862-638e1b362e22 # Image Position [L|R]
            handle: null
            instructions: null
            label: 'Media Position [L|R]'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d7e244f7-6015-4a5c-8426-5cf03eb4ee40
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 524c6e05-4d16-4e49-86a1-edfb5ff0e70c # Animation Settings
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d4e5e674-e63c-4ce9-a5ec-8dbfa983f78c
            userCondition: null
            warning: null
            width: 100
        name: Media
        uid: 869f67e4-c842-4bf1-b576-754def9a0898
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: dfbc0047-f74f-4940-baf3-7f9402fc918e # Background Color
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9d7bd905-54aa-462c-be45-e4b33de0b440
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 28a04878-3d6a-4889-ad36-87cce2dd449e # Padding: Top
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d77b9bc8-b289-4aa3-a0ac-f18f364b1a10
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 040d7db9-375b-4b41-989d-2e38c47b90f6 # Padding: Bottom
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c13ea6a-8ffd-467a-97b3-881f19cafbb3
            userCondition: null
            warning: null
            width: 25
        name: 'Section Settings'
        uid: 92befd9b-7025-4bfb-b1dd-5909c62737c5
        userCondition: null
    thumbFieldKey: null
group: null
groupChildBlockTypes: true
handle: textMedia
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Text+Media
topLevel: true
