childBlocks: null
color: null
conditions: null
description: ''
enabled: true
entryType: null
field: 0ba00a47-4ce1-4c02-a3ca-61119f702d8d # Mega Menu: Links
fieldLayouts:
  fc520549-352e-45d5-b44b-d61b74895950:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: d2cf84b8-da42-48ed-9ffa-4f93da867f96 # Text Link
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 015464fb-daf3-4882-a11c-9c1621cf6517
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a8366a49-97a6-4a33-a567-a948f6a481ac # Section ID
            handle: null
            instructions: 'Section identifier for a specific section of the page, ex: for-churches'
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 641f7825-0a13-443f-b11d-7fb2456a546a
            userCondition: null
            warning: null
            width: 100
        name: 'Text Link'
        uid: e7e70f12-b8f9-423f-98c1-c4ba71534f50
        userCondition: null
    thumbFieldKey: null
group: null
groupChildBlockTypes: true
handle: textLink
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Text Link'
topLevel: false
