childBlocks:
  - factoid1Up
  - factoid2Up
  - factoid3Up
  - button
color: null
conditions: null
description: ''
enabled: true
entryType: null
field: 0914ee96-13fc-4737-ae93-8ab00d611b35 # Page Builder: Blog
fieldLayouts:
  ae7c7b6b-aee4-43eb-8185-12e142f6021d:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7f134341-6c01-4975-9ea9-60df3c3dd5f0 # Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d64b7bc6-5821-410b-8073-0aacf3cc0d50
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 76c2555a-23b9-4d53-8c79-13892f75b970 # Factoid Description Box
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bf5bfa2b-8a2b-481f-a662-4a3f0e58cdaf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 4f1a3081-cb03-47eb-b862-638e1b362e22 # Image Position [L|R]
            handle: null
            instructions: null
            label: 'Factoid Position [L|R]'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a0aa9e90-5b1a-4af8-a067-6f312325cc3b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            elementCondition: null
            type: benf\neo\fieldlayoutelements\ChildBlocksUiElement
            uid: 59790e56-416f-40a6-a650-c5a4db888e4e
            userCondition: null
        name: Factoid
        uid: 2e53026f-7e33-44a0-a312-adc06fc46fd9
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: d24ab695-25c2-4078-b7e4-b936aa667ac6 # Pre-Eyebrow
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e82f9a76-eef5-469b-97db-0b35f713c7c7
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: fb633af9-99e4-499c-b90f-60a8039f3046 # Text Alignment
            handle: null
            instructions: null
            label: 'Pre-Eyebrow Text Alignment'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7bdbbeec-36eb-4c61-98b0-0b428fe46a15
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e39974bd-ec97-4187-be91-a431e1a4fbd7 # Eyebrow
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f6d2ffe-9320-4d5b-a3f8-f07a57c2bc1f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6ab970bd-1621-4c3f-8eeb-6887ac8cbb2c # Heading
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a9e54804-9494-43e3-927a-e4545d33b241
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: d4a66aad-fd77-4abe-97e2-a01cabc77bac # Description
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0cb771e2-2f28-47dd-9279-f1e207d28451
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 17fcc0b6-4e93-425f-9380-11c07300553d # Buttons
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cc21bf4d-f966-4a09-b5d9-29b809e47b00
            userCondition: null
            warning: null
            width: 100
        name: Description
        uid: bc88482a-eaf3-4fce-ab33-634851fc463d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: dfbc0047-f74f-4940-baf3-7f9402fc918e # Background Color
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 22437646-567e-4993-9a6f-f4a035a316eb
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 28a04878-3d6a-4889-ad36-87cce2dd449e # Padding: Top
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fe9d123d-2aac-48b9-a49a-69b94ffda5d8
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 040d7db9-375b-4b41-989d-2e38c47b90f6 # Padding: Bottom
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f9cd47f2-fc7b-45d3-ad04-184a5f0e8b86
            userCondition: null
            warning: null
            width: 25
        name: 'Section Settings'
        uid: bde83cae-4487-413d-bce8-897a46432eed
        userCondition: null
    thumbFieldKey: null
group: null
groupChildBlockTypes: true
handle: textFactoid
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Text+Factoid
topLevel: true
