field: e11568a1-11e3-4147-ae18-1ff01fdcd4f7 # CTA Tile: Small
fieldLayouts:
  9b0a8eec-17d3-458a-8eb4-360216a816fc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 251036cc-4dfd-4b0f-9823-b109a413bd0b # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e8c2be9a-24bf-4bc7-a7b5-1a565e21e08d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: dba75db4-1559-48ba-b4d4-a5e5738429a4 # Stack Image on Mobile
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 606692b5-540b-4a3e-b56f-e5c5b766cfb9
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 160cd5ce-bdfd-4507-b851-369a31a5bbb6 # Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5cc7edee-567a-4216-ad3d-ed0d9ca68d52
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 8cccdb1c-6473-404a-9289-b9a52343d552 # Label: Custom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 54c2d01c-7541-4557-beb8-ad4815fabb4b
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 3b6ab5b3-228a-4f9a-b6ba-5958d0d9daf2 # Icon: Custom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca588bd1-be1c-4e89-8664-c2619fe5c9eb
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: baddf677-8996-4c34-b436-ea8341d9bed3 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 36700fb8-816b-4a20-b4dd-487991c7f76a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 40fb54cb-b959-40bc-8123-44ac2a4c5aa2 # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e3d6dfc0-d641-4389-9f47-ac3516b88b0e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ea398104-dad5-4eb7-aa2b-a5c43f8f694f
        userCondition: null
fields:
  3b6ab5b3-228a-4f9a-b6ba-5958d0d9daf2: # Icon: Custom
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: iconCustom
    instructions: null
    name: 'Icon: Custom'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:ae512cd8-d6a4-49a2-b185-8ba40a87fc1e' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:ae512cd8-d6a4-49a2-b185-8ba40a87fc1e' # Images
      restrictedLocationSubpath: null
      selectionLabel: 'Add an icon'
      showSiteMenu: true
      showUnpermittedFiles: true
      showUnpermittedVolumes: true
      sources:
        - 'volume:ae512cd8-d6a4-49a2-b185-8ba40a87fc1e' # Images
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  8cccdb1c-6473-404a-9289-b9a52343d552: # Label: Custom
    columnSuffix: xcnlgoji
    contentColumnType: text
    fieldGroup: null
    handle: labelCustom
    instructions: null
    name: 'Label: Custom'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  40fb54cb-b959-40bc-8123-44ac2a4c5aa2: # Link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: tileLink
    instructions: null
    name: Link
    searchable: false
    settings:
      allowCustomText: false
      allowTarget: true
      autoNoReferrer: true
      customTextMaxLength: 0
      customTextRequired: false
      defaultLinkName: entry
      defaultText: ''
      enableAllLinkTypes: false
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: true
        email:
          allowAliases: false
          disableValidation: false
          enabled: false
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: false
        url:
          allowAliases: false
          disableValidation: false
          enabled: false
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: none
    type: lenz\linkfield\fields\LinkField
  160cd5ce-bdfd-4507-b851-369a31a5bbb6: # Label
    columnSuffix: hdmefibo
    contentColumnType: string
    fieldGroup: null
    handle: label
    instructions: 'Choose a pre-defined label + icon'
    name: Label
    searchable: false
    settings:
      dataSet: 'CTA Tile Labels'
      type: dropdown
    translationKeyFormat: null
    translationMethod: none
    type: statikbe\configvaluesfield\fields\ConfigValuesFieldField
  251036cc-4dfd-4b0f-9823-b109a413bd0b: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:ae512cd8-d6a4-49a2-b185-8ba40a87fc1e' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: 1
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:ae512cd8-d6a4-49a2-b185-8ba40a87fc1e' # Images
      restrictedLocationSubpath: null
      selectionLabel: 'Add an image'
      showSiteMenu: true
      showUnpermittedFiles: true
      showUnpermittedVolumes: true
      sources:
        - 'volume:ae512cd8-d6a4-49a2-b185-8ba40a87fc1e' # Images
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  baddf677-8996-4c34-b436-ea8341d9bed3: # Heading
    columnSuffix: vpszddxq
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  dba75db4-1559-48ba-b4d4-a5e5738429a4: # Stack Image on Mobile
    columnSuffix: qgprmvnp
    contentColumnType: boolean
    fieldGroup: null
    handle: stackImageOnMobile
    instructions: null
    name: 'Stack Image on Mobile'
    searchable: false
    settings:
      default: false
      offLabel: 'No'
      onLabel: 'Yes'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: tile
name: Tile
sortOrder: 1
