field: 24a26f70-67f3-45a7-8828-d33f091c1508 # Home: Tile - Wide
fieldLayouts:
  d0b547f6-3747-4255-9f83-81f97faeac1c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4d7096da-e00f-4539-976f-2ab6e40967b7 # Thumbnail
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b5fd3d09-2d5b-4d2b-8dfa-65e9f3356785
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: d46a26f8-acd0-4f06-8f57-f8e755cbcddb # Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8bf00eff-e5c6-4299-a318-8be0884c9d71
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: ab7e2d93-36c3-4838-bcb0-b9378b70308a # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 930c6e46-26e4-4323-b975-7deac6d03696
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 74ee5a5e-4ff2-4cf1-b268-c3c2ff67c2b9 # Video
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ebb07b3e-ab67-405d-a722-1cf6bb40efc6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 43637cf7-8578-4d01-a546-810990b395df
        userCondition: null
fields:
  4d7096da-e00f-4539-976f-2ab6e40967b7: # Thumbnail
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: thumbnail
    instructions: null
    name: Thumbnail
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:ae512cd8-d6a4-49a2-b185-8ba40a87fc1e' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:ae512cd8-d6a4-49a2-b185-8ba40a87fc1e' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Add a thumbnail image'
      showSiteMenu: true
      showUnpermittedFiles: true
      showUnpermittedVolumes: true
      sources:
        - 'volume:ae512cd8-d6a4-49a2-b185-8ba40a87fc1e' # Images
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  74ee5a5e-4ff2-4cf1-b268-c3c2ff67c2b9: # Video
    columnSuffix: tbcowjcz
    contentColumnType: string
    fieldGroup: null
    handle: video
    instructions: "1. Click the [+ Add a video] button\r\n2. Click the [EMBED] button at the bottom of the file picker window\r\n3. Copy and paste the video URL into the field that appears\r\n4. Click [Save] button after video preview appears\r\n5. Click [Select] button at the bottom of the file picker window "
    name: Video
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:dd3266ad-0d93-46fc-89f3-e57ebce2178c' # Videos
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:dd3266ad-0d93-46fc-89f3-e57ebce2178c' # Videos
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Add a video'
      showSiteMenu: true
      showUnpermittedFiles: true
      showUnpermittedVolumes: true
      sources:
        - 'volume:dd3266ad-0d93-46fc-89f3-e57ebce2178c' # Videos
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  ab7e2d93-36c3-4838-bcb0-b9378b70308a: # Heading
    columnSuffix: vyoyvyhq
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d46a26f8-acd0-4f06-8f57-f8e755cbcddb: # Label
    columnSuffix: zcmdqhxs
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: null
    name: Label
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: videoTile
name: 'Video Tile'
sortOrder: 1
