columnSuffix: null
contentColumnType: string
handle: accordionItems
instructions: null
name: 'Accordion Items'
searchable: true
settings:
  entryTypes:
    -
      uid: e157403f-fd93-4372-be54-35cd7249d219
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
