columnSuffix: null
contentColumnType: string
handle: alertBar
instructions: null
name: 'Alert Bar'
searchable: false
settings:
  entryTypes:
    -
      uid: 18f80578-ea92-42da-a34e-61be2cddec76
  maxEntries: 1
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
