columnSuffix: emqtrsxt
contentColumnType: string
fieldGroup: 07a87980-eb4d-4710-896e-772170d1d21d # Section Settings
handle: backgroundColor
instructions: null
name: 'Background Color'
searchable: true
settings:
  dataSet: 'Section Backgrounds'
  type: dropdown
translationKeyFormat: null
translationMethod: none
type: statikbe\configvaluesfield\fields\ConfigValuesFieldField
