columnSuffix: emqtrsxt
handle: backgroundColor
instructions: null
name: 'Background Color'
searchable: true
settings:
  dataSet: 'Section Backgrounds'
  type: dropdown
translationKeyFormat: null
translationMethod: none
type: statikbe\configvaluesfield\fields\ConfigValuesFieldField
