columnSuffix: crwcrjan
handle: backgroundColor5
instructions: null
name: 'Factoid Description Box - Background Color'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - '--'
        -
          - value
          - ''
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Navy
        -
          - value
          - bg-primary
        -
          - icon
          - circle
        -
          - color
          - '#231f5b'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Navy Light'
        -
          - value
          - bg-primary-light
        -
          - icon
          - circle
        -
          - color
          - '#4039a7'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Navy Extralight'
        -
          - value
          - bg-primary-extralight
        -
          - icon
          - circle
        -
          - color
          - '#e9e8f7'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Gold
        -
          - value
          - bg-secondary
        -
          - icon
          - circle
        -
          - color
          - '#c19d68'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Gold Light'
        -
          - value
          - bg-secondary-light
        -
          - icon
          - circle
        -
          - color
          - '#dfccb0'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Gold Extralight'
        -
          - value
          - bg-secondary-extralight
        -
          - icon
          - circle
        -
          - color
          - '#f5efe7'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Blue
        -
          - value
          - bg-tertiary
        -
          - icon
          - circle
        -
          - color
          - '#3c3f9b'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Black
        -
          - value
          - bg-black
        -
          - icon
          - circle
        -
          - color
          - '#333333'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Dark
        -
          - value
          - bg-dark
        -
          - icon
          - circle
        -
          - color
          - '#212529'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Silver
        -
          - value
          - bg-silver
        -
          - icon
          - circle
        -
          - color
          - '#f5f5f5'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - White
        -
          - value
          - bg-white
        -
          - icon
          - circle
        -
          - color
          - '#ffffff'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
