columnSuffix: null
contentColumnType: string
fieldGroup: aa92801f-a617-4884-96f7-2f325db59d9e # Element Fields
handle: blogEntries
instructions: null
name: 'Blog Entries'
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: 'Add a Blog Entry'
  showSiteMenu: true
  sources:
    - 'section:f6513c96-9a09-43f8-b901-27de58e1f28e'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
