columnSuffix: gukpxksf
handle: btnStyle
instructions: null
name: 'Buttons - Style'
searchable: false
settings:
  dataSet: 'Button Style'
  type: dropdown
translationKeyFormat: null
translationMethod: none
type: statikbe\configvaluesfield\fields\ConfigValuesFieldField
