columnSuffix: eqvkrypm
handle: buttonLabel
instructions: null
name: 'Resource Cards - Button Label'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: Download
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
