columnSuffix: null
handle: buttons2
instructions: null
name: 'Popup - Simple - Buttons'
searchable: false
settings:
  contentTable: ''
  createButtonLabel: null
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - c36259c6-bea8-45bc-b432-ef40fda5b6d0 # Popup - Simple - Buttons Block
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
