columnSuffix: ledemsdw
handle: buttonStyle2
instructions: null
name: 'Popup - Simple - Buttons - Button Style'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - '--'
        -
          - value
          - ''
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Solid Navy'
        -
          - value
          - btn-primary
        -
          - icon
          - circle
        -
          - color
          - '#231f5b'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Solid Gold'
        -
          - value
          - btn-secondary
        -
          - icon
          - circle
        -
          - color
          - '#c19d68'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Solid Blue'
        -
          - value
          - btn-tertiary
        -
          - icon
          - circle
        -
          - color
          - '#3c3f9b'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Solid Dark'
        -
          - value
          - btn-dark
        -
          - icon
          - circle
        -
          - color
          - '#212529'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Solid Silver'
        -
          - value
          - btn-silver
        -
          - icon
          - circle
        -
          - color
          - '#f5f5f5'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Solid White'
        -
          - value
          - btn-white
        -
          - icon
          - circle
        -
          - color
          - '#ffffff'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Solid Black'
        -
          - value
          - btn-black
        -
          - icon
          - circle
        -
          - color
          - '#333333'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Outline Navy'
        -
          - value
          - btn-outline-primary
        -
          - icon
          - circle
        -
          - color
          - '#231f5b'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Outline Gold'
        -
          - value
          - btn-outline-secondary
        -
          - icon
          - circle
        -
          - color
          - '#c19d68'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Outline Blue'
        -
          - value
          - btn-outline-tertiary
        -
          - icon
          - circle
        -
          - color
          - '#3c3f9b'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Outline Dark'
        -
          - value
          - btn-outline-dark
        -
          - icon
          - circle
        -
          - color
          - '#212529'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Outline Silver'
        -
          - value
          - btn-outline-silver
        -
          - icon
          - circle
        -
          - color
          - '#f5f5f5'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Outline White'
        -
          - value
          - btn-outline-white
        -
          - icon
          - circle
        -
          - color
          - '#ffffff'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Outline Black'
        -
          - value
          - btn-outline-black
        -
          - icon
          - circle
        -
          - color
          - '#333333'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
