columnSuffix: null
handle: buttons
instructions: null
name: Buttons
searchable: true
settings:
  contentTable: ''
  createButtonLabel: null
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 5dee0c7a-6b25-454b-8b3f-58fbac243d82 # Buttons Block
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
