columnSuffix: fjizstal
contentColumnType: string
fieldGroup: fc6163a0-4dcb-460e-9f08-2c9bdbe82bd0 # Text Fields
handle: caption
instructions: null
name: Caption
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: string
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
