columnSuffix: null
handle: cbBackgroundColor
instructions: null
name: 'CB: Background Color'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - '--'
        -
          - value
          - ''
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - White
        -
          - value
          - bg-white
        -
          - icon
          - ''
        -
          - color
          - '#ffffff'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Light Gray'
        -
          - value
          - bg-light
        -
          - icon
          - ''
        -
          - color
          - '#f8f9fa'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Primary
        -
          - value
          - bg-primary
        -
          - icon
          - ''
        -
          - color
          - '#00539B'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Secondary
        -
          - value
          - bg-secondary
        -
          - icon
          - ''
        -
          - color
          - '#6c757d'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
