columnSuffix: null
handle: cbUrl
instructions: null
name: 'CB: URL'
searchable: false
settings:
  maxLength: 255
  placeholder: null
  types:
    - url
translationKeyFormat: null
translationMethod: site
type: craft\fields\Url
