columnSuffix: null
handle: contentBuilder
instructions: null
name: 'Content Builder'
searchable: true
settings:
  createButtonLabel: 'Add Block'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 704ec5d2-710d-4529-90d8-8ea96c8fc596 # CB: Heading Block
    -
      __assoc__:
        -
          - uid
          - 5c593dce-1cac-4609-9d72-1dfb9ba4f3af # CB: Text Block
    -
      __assoc__:
        -
          - uid
          - e5982311-5ac2-4582-9c2f-466017c0c0ce # CB: Image Block
    -
      __assoc__:
        -
          - uid
          - de52741d-93ab-4f36-8caf-8584421f4668 # CB: Embed Code Block
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
