columnSuffix: null
contentColumnType: string
handle: ctaTileLarge
instructions: null
name: 'CTA Tile: Large'
searchable: true
settings:
  entryTypes:
    -
      handle: tile
      uid: 489ff905-09c2-4e5b-a990-e00ceda4050e
  maxEntries: 1
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
