columnSuffix: null
handle: ctaTileLarge
instructions: null
name: 'CTA Tile: Large'
searchable: true
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 489ff905-09c2-4e5b-a990-e00ceda4050e # Tile
        -
          - handle
          - tile
  includeTableView: false
  maxEntries: 1
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
