columnSuffix: null
handle: ctaTileSmall
instructions: null
name: 'CTA Tile: Small'
searchable: true
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - a1c959ad-0f2a-4fc4-8654-11be8c04b62f # Tile
        -
          - handle
          - tile
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
