columnSuffix: null
contentColumnType: string
handle: ctaTileSmall
instructions: null
name: 'CTA Tile: Small'
searchable: true
settings:
  entryTypes:
    -
      handle: tile
      uid: a1c959ad-0f2a-4fc4-8654-11be8c04b62f
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
