columnSuffix: yzailcas
handle: dataTable
instructions: null
name: 'Data Table'
searchable: true
settings:
  columnsAddRowLabel: null
  columnsInstructions: 'Add columns to your table'
  columnsLabel: null
  enableAlignmentColumn: true
  enableWidthColumn: true
  rowsAddRowLabel: null
  rowsInstructions: 'Add rows to your table'
  rowsLabel: null
translationKeyFormat: null
translationMethod: none
type: verbb\tablemaker\fields\TableMakerField
