columnSuffix: null
handle: dataTables
instructions: null
name: 'Data Tables'
searchable: true
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - eee5e319-f63b-458a-8ea2-ae0a83ba319d # Pre-defined Table
    -
      __assoc__:
        -
          - uid
          - ad7213bd-2585-46b4-80ac-945289d706b3 # Rate Table
        -
          - handle
          - rateTable
    -
      __assoc__:
        -
          - uid
          - 2c56ec44-02d8-449f-b55a-ccb4e0f64909 # Custom Table
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
