columnSuffix: cxmpqfkq
contentColumnType: text
handle: description
instructions: null
name: Description
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  columnType: text
  defaultTransform: ''
  enableSourceEditingForNonAdmins: true
  headingLevels:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
  options:
    code:
      indentSequence: '    '
    htmlSupport:
      allow:
        -
          attributes: true
          classes: true
          styles: true
  purifierConfig: null
  purifyHtml: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  toolbar:
    - sourceEditing
    - '|'
    - heading
    - '|'
    - blockQuote
    - codeBlock
    - bold
    - italic
    - bulletedList
    - numberedList
    - link
    - insertImage
    - mediaEmbed
    - fullscreen
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
