columnSuffix: yzdefinn
contentColumnType: boolean
fieldGroup: 0b2d797a-1a89-4e24-8ef6-9d5d39a5d548
handle: disableImageTransforms
instructions: null
name: 'Disable Image Transforms'
searchable: false
settings:
  default: false
  offLabel: Enabled
  onLabel: Disabled
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
