columnSuffix: yzdefinn
handle: disableImageTransforms
instructions: null
name: 'Disable Image Transforms'
searchable: false
settings:
  default: false
  offLabel: Enabled
  onLabel: Disabled
  showLabelsInCards: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
