columnSuffix: yzdefinn
contentColumnType: boolean
handle: disableImageTransforms
instructions: null
name: 'Disable Image Transforms'
searchable: false
settings:
  default: false
  offLabel: Enabled
  onLabel: Disabled
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
