columnSuffix: fjtltnzb
handle: download2
instructions: null
name: 'Buttons - Download'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
  showLabelsInCards: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
