columnSuffix: lmdulxer
contentColumnType: text
fieldGroup: fc6163a0-4dcb-460e-9f08-2c9bdbe82bd0
handle: embedCode
instructions: null
name: 'Embed Code'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: true
  columnType: text
  initialRows: 2
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
