columnSuffix: null
contentColumnType: string
handle: factoidDescriptionBox
instructions: null
name: 'Factoid Description Box'
searchable: true
settings:
  blockTypeFields: 0
  changedFieldIndicator: 1126437317
  entryTypes:
    - 50948af4-8048-4d23-8abf-ddf994ca4832 # Factoid Description Box Block
  fieldLayout: matrix
  maxEntries: null
  maxRows: 1
  minEntries: null
  minRows: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: 'Add a description box'
  staticField: null
  viewMode: blocks
translationKeyFormat: null
translationMethod: none
type: verbb\supertable\fields\SuperTableField
