columnSuffix: null
contentColumnType: string
fieldGroup: 6a0d0683-24f8-47d9-b693-069ad30f6a5d
handle: factoidDescriptionBox
instructions: null
name: 'Factoid Description Box'
searchable: true
settings:
  blockTypeFields: 0
  changedFieldIndicator: 1126437317
  contentTable: '{{%stc_factoiddescriptionbox}}'
  fieldLayout: matrix
  maxRows: 1
  minRows: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: 'Add a description box'
  staticField: null
translationKeyFormat: null
translationMethod: none
type: verbb\supertable\fields\SuperTableField
