columnSuffix: null
contentColumnType: string
handle: form
instructions: null
name: Form
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: 1
  selectionLabel: 'Select form'
  showSiteMenu: true
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: verbb\formie\fields\Forms
