columnSuffix: avaecucj
contentColumnType: boolean
fieldGroup: 0b2d797a-1a89-4e24-8ef6-9d5d39a5d548 # Select Fields
handle: fullViewport
instructions: null
name: 'Full Viewport'
searchable: false
settings:
  default: false
  offLabel: 'No'
  onLabel: 'Yes'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
