columnSuffix: null
contentColumnType: string
fieldGroup: aa92801f-a617-4884-96f7-2f325db59d9e # Element Fields
handle: grantYear
instructions: null
name: 'Grant Year'
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: 1
  selectionLabel: null
  showSiteMenu: true
  source: 'group:bafdb566-dc62-40b5-9a8f-ca3010a690f9' # Grant Years
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
