columnSuffix: null
handle: grantRecipients
instructions: null
name: 'Grant Recipients'
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSearchInput: true
  showSiteMenu: true
  showUnpermittedEntries: true
  showUnpermittedSections: true
  sources:
    - 'section:3dfc7896-c87e-4252-ad06-4a34e187be45' # Grant Recipients
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
