columnSuffix: null
handle: grantYear
instructions: null
name: 'Grant Year'
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: null
  minRelations: 1
  selectionLabel: null
  showSearchInput: true
  showSiteMenu: true
  source: 'group:bafdb566-dc62-40b5-9a8f-ca3010a690f9' # Grant Years
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Categories
