columnSuffix: kskuqcvf
contentColumnType: string
handle: gridWidth
instructions: null
name: 'Grid Width'
searchable: false
settings:
  dataSet: 'Grid Widths'
  type: dropdown
translationKeyFormat: null
translationMethod: none
type: statikbe\configvaluesfield\fields\ConfigValuesFieldField
