columnSuffix: kskuqcvf
contentColumnType: string
fieldGroup: 0b2d797a-1a89-4e24-8ef6-9d5d39a5d548
handle: gridWidth
instructions: null
name: 'Grid Width'
searchable: false
settings:
  dataSet: 'Grid Widths'
  type: dropdown
translationKeyFormat: null
translationMethod: none
type: statikbe\configvaluesfield\fields\ConfigValuesFieldField
