columnSuffix: null
contentColumnType: string
fieldGroup: 6a0d0683-24f8-47d9-b693-069ad30f6a5d
handle: headshotVideos
instructions: null
name: 'Headshot Videos'
searchable: true
settings:
  contentTable: '{{%matrixcontent_headshotvideos}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
