columnSuffix: mbqilrul
handle: heading12
instructions: null
name: 'Factoid Description Box - Heading'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
