columnSuffix: null
contentColumnType: string
handle: headshotVideos
instructions: null
name: 'Headshot Videos'
searchable: true
settings:
  entryTypes:
    -
      uid: 6ad28947-80eb-413a-95d6-899fff1928b4
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
