columnSuffix: yryrawzk
handle: heading5
instructions: 'Override pre-defined heading'
name: 'Data Tables - Pre-defined Table - Heading'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
