columnSuffix: hfnrmlfb
handle: hideBreadcrumbs
instructions: null
name: 'Hide Breadcrumbs'
searchable: false
settings:
  default: false
  offLabel: Shown
  onLabel: Hidden
  showLabelsInCards: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
