columnSuffix: null
contentColumnType: string
fieldGroup: 431ce2c5-de63-4209-b6b9-a5a836a67d82
handle: homeIntro
instructions: null
name: 'Home: Intro'
searchable: true
settings:
  blockTypeFields: 0
  changedFieldIndicator: 2015265685
  columns:
    __assoc__:
      -
        - 643e4c17-f296-47ae-8806-45847ebda838
        -
          __assoc__:
            -
              - width
              - ''
      -
        - ab39e5a8-9059-4669-8998-c898c3c7ed89
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 0d19f0b1-727c-4654-9f11-09b986093f3d
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_homeintro}}'
  fieldLayout: row
  maxRows: null
  minRows: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: null
  staticField: true
translationKeyFormat: null
translationMethod: none
type: verbb\supertable\fields\SuperTableField
