columnSuffix: null
contentColumnType: string
fieldGroup: 431ce2c5-de63-4209-b6b9-a5a836a67d82
handle: homeTileWide
instructions: null
name: 'Home: Tile - Wide'
searchable: true
settings:
  contentTable: '{{%matrixcontent_hometilewide}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
