columnSuffix: null
contentColumnType: string
handle: homeSquareTiles
instructions: 'Insert four square tiles'
name: 'Home: Square Tiles'
searchable: true
settings:
  entryTypes:
    -
      uid: 356681f1-6b5a-48fb-94b8-d856247a3b67
  maxEntries: 4
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
