columnSuffix: null
handle: homeTileWide
instructions: null
name: 'Home: Tile - Wide'
searchable: true
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - be37b343-87c7-4b21-8965-829e7c555685 # Video Tile
    -
      __assoc__:
        -
          - uid
          - 543e6694-6bf5-44ed-936b-11dd6e5ae656 # Image Tile
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
