columnSuffix: null
handle: image4
instructions: null
name: 'Mega Menu: CTAs - CTA - Image'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultPlacement: end
  defaultUploadLocationSource: 'volume:ae512cd8-d6a4-49a2-b185-8ba40a87fc1e' # Images
  defaultUploadLocationSubpath: null
  maintainHierarchy: false
  maxRelations: 1
  minRelations: 1
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:ae512cd8-d6a4-49a2-b185-8ba40a87fc1e' # Images
  restrictedLocationSubpath: null
  selectionLabel: 'Add a thumbnail'
  showSearchInput: true
  showSiteMenu: false
  showUnpermittedFiles: true
  showUnpermittedVolumes: true
  sources:
    - 'volume:ae512cd8-d6a4-49a2-b185-8ba40a87fc1e' # Images
  targetSiteId: null
  validateRelatedElements: false
  viewMode: thumbs
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
