columnSuffix: baqwdruy
handle: imagePosition
instructions: null
name: 'Popup - Side By Side - Image Position'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Left
        -
          - value
          - left
        -
          - icon
          - arrow-left-long-to-line
        -
          - color
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Right
        -
          - value
          - right
        -
          - icon
          - arrow-right-long-to-line
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
