columnSuffix: rysukuug
contentColumnType: string
handle: itemsPerRow
instructions: null
name: 'Items Per Row'
searchable: false
settings:
  columnType: string
  options:
    -
      __assoc__:
        -
          - label
          - 2
        -
          - value
          - 2
        -
          - default
          - 1
    -
      __assoc__:
        -
          - label
          - 3
        -
          - value
          - 3
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 4
        -
          - value
          - 4
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 5
        -
          - value
          - 5
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 6
        -
          - value
          - 6
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
