columnSuffix: hdmefibo
handle: label7
instructions: 'Choose a pre-defined label + icon'
name: 'CTA Tile: Small - Tile - Label'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - '-- No Label --'
        -
          - value
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Loans
        -
          - value
          - loans
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Grants
        -
          - value
          - grants
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Philanthropy
        -
          - value
          - philanthropy
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Investments
        -
          - value
          - investments
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Area Representatives'
        -
          - value
          - area-representatives
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Leadership Ministry'
        -
          - value
          - leadership-ministry
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
