columnSuffix: null
contentColumnType: string
handle: legalLinks
instructions: null
name: 'Legal Links'
searchable: false
settings:
  entryTypes:
    -
      handle: textLink
      uid: fdacfdd8-aa17-4862-b03c-7ed6c0177dee
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
