columnSuffix: null
contentColumnType: string
fieldGroup: 2160ef32-2844-4834-a6c8-c374a3efa675 # Link Fields
handle: legalLinks
instructions: null
name: 'Legal Links'
searchable: false
settings:
  contentTable: '{{%matrixcontent_legallinks}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
