columnSuffix: null
handle: legalLinks
instructions: null
name: 'Legal Links'
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - fdacfdd8-aa17-4862-b03c-7ed6c0177dee # Text Link
        -
          - handle
          - textLink
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
