columnSuffix: ayvkuovt
contentColumnType: text
handle: listSettings
instructions: null
name: 'List Settings'
searchable: false
settings:
  addRowLabel: 'Add a row'
  columnType: text
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - 'List Arrangement'
            -
              - handle
              - arrangement
            -
              - width
              - ''
            -
              - type
              - select
            -
              - options
              -
                -
                  __assoc__:
                    -
                      - label
                      - Grid
                    -
                      - value
                      - grid
                    -
                      - default
                      - true
                -
                  __assoc__:
                    -
                      - label
                      - Inline
                    -
                      - value
                      - inline
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - Vertical
                    -
                      - value
                      - vertical
                    -
                      - default
                      - false
      -
        - col4
        -
          __assoc__:
            -
              - heading
              - 'Grid Columns'
            -
              - handle
              - columns
            -
              - width
              - ''
            -
              - type
              - select
            -
              - options
              -
                -
                  __assoc__:
                    -
                      - label
                      - '12'
                    -
                      - value
                      - col-md-1
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - '6'
                    -
                      - value
                      - col-md-2
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - '4'
                    -
                      - value
                      - col-md-3
                    -
                      - default
                      - true
                -
                  __assoc__:
                    -
                      - label
                      - '3'
                    -
                      - value
                      - col-md-4
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - '2'
                    -
                      - value
                      - col-md-6
                    -
                      - default
                      - false
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - 'Item Alignment'
            -
              - handle
              - alignment
            -
              - width
              - ''
            -
              - type
              - select
            -
              - options
              -
                -
                  __assoc__:
                    -
                      - label
                      - Left
                    -
                      - value
                      - start
                    -
                      - default
                      - true
                -
                  __assoc__:
                    -
                      - label
                      - Center
                    -
                      - value
                      - center
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - Right
                    -
                      - value
                      - end
                    -
                      - default
                      - false
      -
        - col5
        -
          __assoc__:
            -
              - heading
              - 'Item Spacing'
            -
              - handle
              - gap
            -
              - width
              - ''
            -
              - type
              - select
            -
              - options
              -
                -
                  __assoc__:
                    -
                      - label
                      - Large
                    -
                      - value
                      - '5'
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - Normal
                    -
                      - value
                      - '3'
                    -
                      - default
                      - true
                -
                  __assoc__:
                    -
                      - label
                      - Small
                    -
                      - value
                      - '1'
                    -
                      - default
                      - false
  defaults:
    -
      __assoc__:
        -
          - col1
          - grid
        -
          - col4
          - col-md-1
        -
          - col2
          - start
        -
          - col5
          - '5'
        -
          - rowId
          - 80c54202-07d9-4a80-97f9-59150c777cce
  maxRows: null
  minRows: null
  staticRows: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
