columnSuffix: kucqdrts
contentColumnType: text
handle: listItemsSimple
instructions: null
name: 'List Items: Simple'
searchable: false
settings:
  addRowLabel: 'Add a list item'
  columnType: text
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - 'List Item'
            -
              - handle
              - listItem
            -
              - width
              - ''
            -
              - type
              - singleline
  defaults: null
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
