columnSuffix: null
contentColumnType: string
fieldGroup: dbd3cd32-4e50-4ba5-8894-bbf8b63b3278 # Mega Menu Fields
handle: megaMenuLinks
instructions: null
name: 'Mega Menu: Links'
searchable: false
settings:
  maxBlocks: null
  maxLevels: null
  maxTopBlocks: null
  minBlocks: null
  minLevels: null
  minTopBlocks: null
  newBlockButtonLabel: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: benf\neo\Field
