columnSuffix: null
contentColumnType: string
handle: megaMenuCtas
instructions: null
name: 'Mega Menu: CTAs'
searchable: false
settings:
  entryTypes:
    -
      uid: 5ecdb404-4694-4031-a4a8-b1a523c6d775
    -
      uid: a6fd1543-ece4-4710-ad3b-195db37614a1
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
