columnSuffix: null
contentColumnType: string
fieldGroup: aa92801f-a617-4884-96f7-2f325db59d9e # Element Fields
handle: newsStories
instructions: null
name: 'News Stories'
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: 'Add a News Story'
  showSiteMenu: true
  sources:
    - 'section:72143de2-34b2-4912-87dc-02d8eb4a1a0f' # News
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
