columnSuffix: null
handle: openAnAccountTable
instructions: null
name: 'Open An Account Table'
searchable: true
settings:
  contentTable: ''
  createButtonLabel: null
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 2332bc88-0131-4224-a56c-f80808febce7 # Open An Account Table Block
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
