columnSuffix: krfzahjp
handle: paddingSides
instructions: null
name: 'Padding: Sides'
searchable: true
settings:
  default: true
  offLabel: null
  onLabel: null
  showLabelsInCards: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
