columnSuffix: yfzgyuqf
contentColumnType: boolean
handle: paddingTop
instructions: null
name: 'Padding: Top'
searchable: true
settings:
  default: true
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
