columnSuffix: yfzgyuqf
handle: paddingTop
instructions: null
name: 'Padding: Top'
searchable: true
settings:
  default: true
  offLabel: null
  onLabel: null
  showLabelsInCards: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
