columnSuffix: krfzahjp
contentColumnType: boolean
handle: paddingSides
instructions: null
name: 'Padding: Sides'
searchable: true
settings:
  default: true
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
