columnSuffix: null
contentColumnType: string
fieldGroup: bf0e4db0-9861-4bba-b0d0-98bafe12bc6c # Page Builders
handle: pageBuilderLogin
instructions: null
name: 'Page Builder: Login'
searchable: false
settings:
  maxBlocks: null
  maxLevels: null
  maxTopBlocks: null
  minBlocks: null
  minLevels: null
  minTopBlocks: null
  newBlockButtonLabel: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: benf\neo\Field
