columnSuffix: null
handle: pages
instructions: null
name: Pages
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSearchInput: true
  showSiteMenu: true
  showUnpermittedEntries: true
  showUnpermittedSections: true
  sources:
    - 'section:227624d3-daa5-4f3e-a948-9929f9ff894d'
  targetSiteId: null
  validateRelatedElements: true
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
