columnSuffix: null
contentColumnType: string
fieldGroup: aa92801f-a617-4884-96f7-2f325db59d9e
handle: pages
instructions: null
name: Pages
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: true
  sources:
    - 'section:227624d3-daa5-4f3e-a948-9929f9ff894d'
  targetSiteId: null
  validateRelatedElements: true
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
