columnSuffix: null
contentColumnType: string
fieldGroup: bf0e4db0-9861-4bba-b0d0-98bafe12bc6c # Page Builders
handle: pageHeader
instructions: null
name: 'Page Header'
searchable: true
settings:
  maxBlocks: null
  maxLevels: null
  maxTopBlocks: 1
  minBlocks: null
  minLevels: null
  minTopBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: benf\neo\Field
