columnSuffix: null
contentColumnType: string
handle: popup
instructions: null
name: Popup
searchable: false
settings:
  entryTypes:
    -
      uid: f2b48427-ac90-47d4-bab3-abe8535591f5
    -
      uid: 1cb829c4-b6d2-45ce-914f-36636623179e
  maxEntries: 1
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
