columnSuffix: jeehktdg
contentColumnType: string
handle: positionLCR
instructions: null
name: 'Position[L|C|R]'
searchable: false
settings:
  default: ''
  options:
    __assoc__:
      -
        - left
        - '1'
      -
        - center
        - '1'
      -
        - right
        - '1'
      -
        - full
        - ''
      -
        - drop-left
        - ''
      -
        - drop-right
        - ''
translationKeyFormat: null
translationMethod: none
type: rias\positionfieldtype\fields\Position
