columnSuffix: jeehktdg
handle: positionLCR
instructions: null
name: 'Position[L|C|R]'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Left
        -
          - value
          - left
        -
          - icon
          - arrow-left-long-to-line
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Center
        -
          - value
          - center
        -
          - icon
          - objects-align-center-horizontal
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Right
        -
          - value
          - right
        -
          - icon
          - arrow-right-long-to-line
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
