columnSuffix: tfohxcxz
contentColumnType: text
fieldGroup: fc6163a0-4dcb-460e-9f08-2c9bdbe82bd0
handle: sectionId
instructions: 'Enter a url-friendly identifier for this section of the page. Use all lowercase letters and dashes instead of spaces. Ex: for-churches, or impact-investing. Link to this section with a URL like /impact-investing/impact-notes#for-churches'
name: 'Section ID'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: true
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: 'ex: section-identifier'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
