columnSuffix: sroqnjpv
contentColumnType: text
handle: seo
instructions: null
name: SEO
searchable: true
settings:
  elementDisplayPreviewType: google
  facebookEnabledFields:
    - seoPreview
    - ogTitle
    - ogDescription
    - ogImage
  facebookTabEnabled: '1'
  generalEnabledFields:
    - seoTitle
    - seoDescription
    - seoImage
  generalTabEnabled: '1'
  sitemapEnabledFields: ''
  sitemapTabEnabled: ''
  twitterEnabledFields:
    - seoPreview
    - twitterCardType
    - twitterTitle
    - twitterDescription
    - twitterImage
  twitterTabEnabled: '1'
translationKeyFormat: null
translationMethod: none
type: nystudio107\seomatic\fields\SeoSettings
