columnSuffix: ekmvxche
contentColumnType: boolean
handle: showEntryTitle
instructions: null
name: 'Show Entry Title'
searchable: false
settings:
  default: true
  offLabel: Hide
  onLabel: Show
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
