columnSuffix: ynvkgdlb
handle: size
instructions: null
name: 'Section Heading - Size'
searchable: true
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - 'H1 (Largest)'
        -
          - value
          - h1
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'H2 (Large)'
        -
          - value
          - h2
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'H3 (Medium)'
        -
          - value
          - h3
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'H4 (Small)'
        -
          - value
          - h4
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'H5 (Smallest)'
        -
          - value
          - h5
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
