columnSuffix: ahbgerja
contentColumnType: boolean
handle: stackedUniformButtons
instructions: null
name: 'Stacked Uniform Buttons'
searchable: false
settings:
  default: false
  offLabel: Inline
  onLabel: Stacked
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
