columnSuffix: ahbgerja
handle: stackedUniformButtons
instructions: null
name: 'Stacked Uniform Buttons'
searchable: false
settings:
  default: false
  offLabel: Inline
  onLabel: Stacked
  showLabelsInCards: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
