columnSuffix: hhltbpmh
contentColumnType: string(7)
fieldGroup: 0b2d797a-1a89-4e24-8ef6-9d5d39a5d548
handle: textSize
instructions: null
name: 'Text Size'
searchable: false
settings:
  columnType: null
  options:
    -
      __assoc__:
        -
          - label
          - Default
        -
          - value
          - default
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Large
        -
          - value
          - large
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Small
        -
          - value
          - small
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
