columnSuffix: nafufeyw
contentColumnType: string
handle: textAlignment
instructions: null
name: 'Text Alignment'
searchable: false
settings:
  columnType: string
  options:
    -
      __assoc__:
        -
          - label
          - Left
        -
          - value
          - start
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Center
        -
          - value
          - center
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Right
        -
          - value
          - end
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
