columnSuffix: null
contentColumnType: string
handle: textLinks
instructions: null
name: 'Text Links'
searchable: true
settings:
  entryTypes:
    -
      uid: cb377aa9-4075-4012-9aed-7f7baf560233
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
