columnSuffix: bzibguhd
handle: textAlignment3
instructions: null
name: 'Popup - Side By Side - Text Alignment'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Left
        -
          - value
          - text-start
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Center
        -
          - value
          - text-center
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
