columnSuffix: nixwunvf
handle: textColor2
instructions: null
name: 'Popup - Simple - Text Color'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - '--'
        -
          - value
          - ''
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Navy
        -
          - value
          - text-primary
        -
          - icon
          - circle
        -
          - color
          - '#231f5b'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Gold
        -
          - value
          - text-secondary
        -
          - icon
          - circle
        -
          - color
          - '#c19d68'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Blue
        -
          - value
          - text-tertiary
        -
          - icon
          - circle
        -
          - color
          - '#3c3f9b'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Black
        -
          - value
          - text-black
        -
          - icon
          - circle
        -
          - color
          - '#333333'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Dark
        -
          - value
          - text-dark
        -
          - icon
          - circle
        -
          - color
          - '#212529'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Silver
        -
          - value
          - text-silver
        -
          - icon
          - circle
        -
          - color
          - '#f5f5f5'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - White
        -
          - value
          - text-white
        -
          - icon
          - circle
        -
          - color
          - '#ffffff'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
