columnSuffix: nixwunvf
handle: textColor2
instructions: null
name: 'Popup - Simple - Text Color'
searchable: false
settings:
  dataSet: 'Text Colors'
  type: dropdown
translationKeyFormat: null
translationMethod: none
type: statikbe\configvaluesfield\fields\ConfigValuesFieldField
