columnSuffix: jlwmgrqc
contentColumnType: string
handle: textColor
instructions: null
name: 'Text Color'
searchable: false
settings:
  dataSet: 'Text Colors'
  type: dropdown
translationKeyFormat: null
translationMethod: none
type: statikbe\configvaluesfield\fields\ConfigValuesFieldField
