columnSuffix: loymhkam
contentColumnType: string
fieldGroup: 0b2d797a-1a89-4e24-8ef6-9d5d39a5d548 # Select Fields
handle: themeColor
instructions: null
name: 'Theme Color'
searchable: false
settings:
  dataSet: 'CSS Color Classes'
  type: dropdown
translationKeyFormat: null
translationMethod: none
type: statikbe\configvaluesfield\fields\ConfigValuesFieldField
