columnSuffix: loymhkam
handle: themeColor
instructions: null
name: 'Theme Color'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - '--'
        -
          - value
          - ''
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Navy
        -
          - value
          - primary
        -
          - icon
          - circle
        -
          - color
          - '#231f5b'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Gold
        -
          - value
          - secondary
        -
          - icon
          - circle
        -
          - color
          - '#c19d68'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Gold Light'
        -
          - value
          - secondary-light
        -
          - icon
          - circle
        -
          - color
          - '#dfccb0'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Gold Extralight'
        -
          - value
          - secondary-extralight
        -
          - icon
          - circle
        -
          - color
          - '#f5efe7'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Blue
        -
          - value
          - tertiary
        -
          - icon
          - circle
        -
          - color
          - '#3c3f9b'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Black
        -
          - value
          - black
        -
          - icon
          - circle
        -
          - color
          - '#333333'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Dark
        -
          - value
          - dark
        -
          - icon
          - circle
        -
          - color
          - '#212529'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Silver
        -
          - value
          - silver
        -
          - icon
          - circle
        -
          - color
          - '#f5f5f5'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - White
        -
          - value
          - white
        -
          - icon
          - circle
        -
          - color
          - '#ffffff'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
