columnSuffix: null
contentColumnType: string
handle: thumbnail
instructions: null
name: Thumbnail
searchable: true
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: false
  allowedKinds:
    - image
  branchLimit: null
  defaultUploadLocationSource: 'volume:ae512cd8-d6a4-49a2-b185-8ba40a87fc1e' # Images
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:ae512cd8-d6a4-49a2-b185-8ba40a87fc1e' # Images
  restrictedLocationSubpath: null
  selectionLabel: 'Add an image'
  showSiteMenu: true
  showUnpermittedFiles: true
  showUnpermittedVolumes: true
  sources:
    - 'volume:ae512cd8-d6a4-49a2-b185-8ba40a87fc1e' # Images
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
