columnSuffix: xjmxbfwv
contentColumnType: string(255)
handle: website
instructions: null
name: Website
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
