columnSuffix: xjmxbfwv
contentColumnType: string(255)
fieldGroup: fc6163a0-4dcb-460e-9f08-2c9bdbe82bd0
handle: website
instructions: null
name: Website
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
