changedFieldIndicator: null
field: da39494d-b4b7-4e57-8c52-887a18f71959
fieldLayouts:
  336639be-8a62-45e7-a2cf-c5e1c40c0108:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b613c984-854f-41b5-baea-92cd77be6d0c
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef4c4332-c85b-4479-9832-7482659b196d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d1b1fa3e-1c0b-4a6d-b0b3-dd358fa59f66
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca262393-41e5-491b-b796-e239b8188e84
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d3166c3a-ca64-4122-be3f-716e818e0868
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0621076f-9058-4f83-b364-b06583f1f3ff
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1f41377c-9452-4c44-85f2-23bcfbec5b44
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df51f173-4d05-461f-8801-3cf37737b0f9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 95ae342c-25b0-4c72-84f4-26a24d3182b2
        userCondition: null
fields:
  1f41377c-9452-4c44-85f2-23bcfbec5b44:
    columnSuffix: eqvkrypm
    contentColumnType: text
    fieldGroup: null
    handle: buttonLabel
    instructions: null
    name: 'Button Label'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: Download
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b613c984-854f-41b5-baea-92cd77be6d0c:
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: resource
    instructions: null
    name: Resource
    searchable: true
    settings:
      allowCustomText: true
      allowTarget: true
      autoNoReferrer: true
      customTextMaxLength: 0
      customTextRequired: false
      defaultLinkName: asset
      defaultText: Download
      enableAllLinkTypes: false
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: true
        email:
          allowAliases: false
          disableValidation: false
          enabled: false
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: false
        url:
          allowAliases: false
          disableValidation: false
          enabled: false
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: none
    type: lenz\linkfield\fields\LinkField
  d1b1fa3e-1c0b-4a6d-b0b3-dd358fa59f66:
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: thumbnail
    instructions: null
    name: Thumbnail
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: false
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:ae512cd8-d6a4-49a2-b185-8ba40a87fc1e'
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:ae512cd8-d6a4-49a2-b185-8ba40a87fc1e'
      restrictedLocationSubpath: null
      selectionLabel: 'Add an image'
      showSiteMenu: true
      showUnpermittedFiles: true
      showUnpermittedVolumes: true
      sources:
        - 'volume:ae512cd8-d6a4-49a2-b185-8ba40a87fc1e'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  d3166c3a-ca64-4122-be3f-716e818e0868:
    columnSuffix: gqntnjwz
    contentColumnType: text
    fieldGroup: null
    handle: cardTitle
    instructions: null
    name: 'Card Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: 'Asset title'
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
