columnSuffix: null
contentColumnType: string
fieldGroup: aa92801f-a617-4884-96f7-2f325db59d9e # Element Fields
handle: grantRecipient
instructions: null
name: 'Grant Recipient'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Entry
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\entries\EntryCondition
  selectionLabel: null
  showSiteMenu: true
  sources:
    - 'section:3dfc7896-c87e-4252-ad06-4a34e187be45' # Grant Recipients
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
