columnSuffix: ulibijxb
contentColumnType: text
fieldGroup: 6a0d0683-24f8-47d9-b693-069ad30f6a5d # Matrix Fields
handle: rateTable
instructions: null
name: 'Rate Table'
searchable: true
settings:
  addRowLabel: 'Add a row'
  columnType: text
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Heading
            -
              - handle
              - heading
            -
              - width
              - 25%
            -
              - type
              - singleline
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - '1 Year'
            -
              - handle
              - yr1
            -
              - width
              - 15%
            -
              - type
              - singleline
      -
        - col3
        -
          __assoc__:
            -
              - heading
              - '2 Year'
            -
              - handle
              - yr2
            -
              - width
              - 15%
            -
              - type
              - singleline
      -
        - col4
        -
          __assoc__:
            -
              - heading
              - '3 Year'
            -
              - handle
              - yr3
            -
              - width
              - 15%
            -
              - type
              - singleline
      -
        - col5
        -
          __assoc__:
            -
              - heading
              - '4 Year'
            -
              - handle
              - yr4
            -
              - width
              - 15%
            -
              - type
              - singleline
      -
        - col6
        -
          __assoc__:
            -
              - heading
              - '5 Year'
            -
              - handle
              - yr5
            -
              - width
              - 15%
            -
              - type
              - singleline
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
        -
          - col2
          - '1 Year'
        -
          - col3
          - '2 Year'
        -
          - col4
          - '3 Year'
        -
          - col5
          - '4 Year'
        -
          - col6
          - '5 Year'
    -
      __assoc__:
        -
          - col1
          - Rates
        -
          - col2
          - ''
        -
          - col3
          - ''
        -
          - col4
          - ''
        -
          - col5
          - ''
        -
          - col6
          - ''
    -
      __assoc__:
        -
          - col1
          - 'Average Percentage Yield (APY)'
        -
          - col2
          - ''
        -
          - col3
          - ''
        -
          - col4
          - ''
        -
          - col5
          - ''
        -
          - col6
          - ''
  maxRows: null
  minRows: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
