columnSuffix: null
contentColumnType: string
fieldGroup: aa92801f-a617-4884-96f7-2f325db59d9e # Element Fields
handle: video
instructions: "1. Click the [+ Add a video] button\r\n2. Click the [EMBED] button at the bottom of the file picker window\r\n3. Copy and paste the video URL into the field that appears\r\n4. Click [Save] button after video preview appears\r\n5. Click [Select] button at the bottom of the file picker window "
name: Video
searchable: true
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: false
  allowedKinds: null
  branchLimit: null
  defaultUploadLocationSource: 'volume:dd3266ad-0d93-46fc-89f3-e57ebce2178c' # Videos
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  previewMode: full
  restrictFiles: false
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:ae512cd8-d6a4-49a2-b185-8ba40a87fc1e' # Images
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: 'Add a video'
  showSiteMenu: true
  showUnpermittedFiles: true
  showUnpermittedVolumes: true
  sources:
    - 'volume:dd3266ad-0d93-46fc-89f3-e57ebce2178c' # Videos
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
