changedFieldIndicator: 1180672080
field: d3ccac65-2f19-4621-b98f-cb5f46bf796d # Home: Feature Tile
fieldLayouts:
  45c880df-3252-46c4-afc9-82cac4860991:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f126506f-a32d-40b2-9d16-466e4201be40 # Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4aa9d03-671a-4f4a-b56d-9b8a54505984
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2bd2d918-16fc-4147-9b16-0a5c2a448d3e # Label: Custom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e5ff610-851a-4fa6-b232-f65a8e06c7db
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bb9e3568-5ca9-4a9a-8534-c5e97ea203d7 # Icon: Custom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2baaa0fe-3a9f-4a38-95a4-62d6ee2afeb4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dc0ed69d-1dd6-496a-ab73-dea06d776bc0 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a24ec40-9f45-4be5-9e93-2f380f169553
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4cf16f08-8357-449b-a33e-172385d1c66e # CTA Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d5689f3b-eac4-4f02-9616-20e438768d19
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e9beb911-37b2-4bef-9d5d-9ce2c252767f
        userCondition: null
fields:
  2bd2d918-16fc-4147-9b16-0a5c2a448d3e: # Label: Custom
    columnSuffix: mabbmqve
    contentColumnType: text
    fieldGroup: null
    handle: labelCustom
    instructions: null
    name: 'Label: Custom'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  4cf16f08-8357-449b-a33e-172385d1c66e: # CTA Link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: ctaLink
    instructions: null
    name: 'CTA Link'
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: true
      autoNoReferrer: true
      customTextMaxLength: 0
      customTextRequired: true
      defaultLinkName: entry
      defaultText: ''
      enableAllLinkTypes: false
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: true
        email:
          allowAliases: false
          disableValidation: false
          enabled: false
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: false
        url:
          allowAliases: false
          disableValidation: false
          enabled: false
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: none
    type: lenz\linkfield\fields\LinkField
  bb9e3568-5ca9-4a9a-8534-c5e97ea203d7: # Icon: Custom
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: iconCustom
    instructions: null
    name: 'Icon: Custom'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:ae512cd8-d6a4-49a2-b185-8ba40a87fc1e' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:ae512cd8-d6a4-49a2-b185-8ba40a87fc1e' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Add an icon'
      showSiteMenu: true
      showUnpermittedFiles: true
      showUnpermittedVolumes: true
      sources:
        - 'volume:ae512cd8-d6a4-49a2-b185-8ba40a87fc1e' # Images
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  dc0ed69d-1dd6-496a-ab73-dea06d776bc0: # Heading
    columnSuffix: pbmujoxo
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f126506f-a32d-40b2-9d16-466e4201be40: # Label
    columnSuffix: pqdrxtly
    contentColumnType: string
    fieldGroup: null
    handle: label
    instructions: 'Choose a pre-defined label+icon'
    name: Label
    searchable: false
    settings:
      dataSet: 'CTA Tile Labels'
      type: dropdown
    translationKeyFormat: null
    translationMethod: none
    type: statikbe\configvaluesfield\fields\ConfigValuesFieldField
