changedFieldIndicator: 385242149
field: c67bfc40-e256-429b-8bc2-bf32fdbf8e43 # Home: Intro
fieldLayouts:
  ac482144-0af6-4767-90da-4d1d39e61395:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 643e4c17-f296-47ae-8806-45847ebda838 # Pre Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 23639c18-8cb3-4f6e-83df-4764f1f41c0f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ab39e5a8-9059-4669-8998-c898c3c7ed89 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c9a8f7b-7c6f-4169-94af-776247712f21
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0d19f0b1-727c-4654-9f11-09b986093f3d # CTA Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3b4f00ae-5294-434a-b4a4-2c31c13ac710
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a6ec9725-02c5-48b7-9b8b-773e95ca5395
        userCondition: null
fields:
  0d19f0b1-727c-4654-9f11-09b986093f3d: # CTA Link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: ctaLink
    instructions: null
    name: 'CTA Link'
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: true
      autoNoReferrer: true
      customTextMaxLength: 0
      customTextRequired: true
      defaultLinkName: entry
      defaultText: ''
      enableAllLinkTypes: false
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: true
        email:
          allowAliases: false
          disableValidation: false
          enabled: false
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: false
        url:
          allowAliases: false
          disableValidation: false
          enabled: false
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: none
    type: lenz\linkfield\fields\LinkField
  643e4c17-f296-47ae-8806-45847ebda838: # Pre Heading
    columnSuffix: qlmewnqv
    contentColumnType: text
    fieldGroup: null
    handle: preHeading
    instructions: null
    name: 'Pre Heading'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ab39e5a8-9059-4669-8998-c898c3c7ed89: # Heading
    columnSuffix: otvxllsw
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
