changedFieldIndicator: 80823379
field: c1bd1034-0a53-48f2-8b9c-d886fd341b7c # Factoid Row
fieldLayouts:
  60b18f8d-0455-4d16-978e-d48797bc1d25:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4e214763-873d-49f2-b594-cc965769e9d2 # Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5d7500e1-e144-4c73-bfea-7b273bc5d80f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a0c65643-d891-45f2-bbf0-a4b756c0349d # Stat
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 86cb227a-7fc5-4836-88e1-a17c0a3b7065
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7923bc83-5cfb-4818-8b77-0d5b666bf979 # Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0b02f6a2-f688-4d39-9504-c1cf705f04d8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f9bdd6dc-04a2-4cd7-b37c-968de8fd4d62
        userCondition: null
fields:
  4e214763-873d-49f2-b594-cc965769e9d2: # Icon
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: icon
    instructions: null
    name: Icon
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:ae512cd8-d6a4-49a2-b185-8ba40a87fc1e' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:ae512cd8-d6a4-49a2-b185-8ba40a87fc1e' # Images
      restrictedLocationSubpath: null
      selectionLabel: 'Add an icon'
      showSiteMenu: false
      showUnpermittedFiles: true
      showUnpermittedVolumes: true
      sources:
        - 'volume:ae512cd8-d6a4-49a2-b185-8ba40a87fc1e' # Images
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  7923bc83-5cfb-4818-8b77-0d5b666bf979: # Label
    columnSuffix: syrnwcjc
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: null
    name: Label
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a0c65643-d891-45f2-bbf0-a4b756c0349d: # Stat
    columnSuffix: tajshosi
    contentColumnType: text
    fieldGroup: null
    handle: stat
    instructions: null
    name: Stat
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
