fieldLayouts:
  81226ade-9924-411c-9682-f5d421b68c18:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: af50f0a7-58c9-4c5d-9fff-0a81017e0472
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9d7fafd1-35d2-468a-929a-b88e876f64e2 # Email
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f2afbba-2763-414d-997e-5cc76ba07620
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: dd9615db-bd5d-4050-9139-1b6174979ce8 # Phone
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dca032a7-4a93-4dcc-93ac-21c88a33ad76
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 7f134341-6c01-4975-9ea9-60df3c3dd5f0 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b17bd168-fdb6-4efd-ac22-2ba9488d1ed9
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: aa3d7fc1-1a22-4fff-8fe2-28dd1ab8388e # Pre-heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1e388b31-7087-4de5-abd7-ed9adbbcaa47
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 6ab970bd-1621-4c3f-8eeb-6887ac8cbb2c # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e219101-8ea3-4cf4-9e31-20cd634ca9b7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d4a66aad-fd77-4abe-97e2-a01cabc77bac # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c1f5886b-8ac0-4e75-ac45-dae1db660b48
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3eb83c90-8106-4f49-9f36-999625fb38ce
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e9b0d2b3-481f-4b12-bf3c-4fc241f7e6f8 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9ad8cafe-f838-425f-a1c2-2e8e1afb911c
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: a6b23cdc-897e-4137-b340-2669f321f71f
        userCondition: null
handle: person
hasTitleField: true
name: Person
section: 61a1068b-a537-4bde-85ac-b0fe8f04946e # Team
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
