defaultPlacement: end
enableVersioning: true
handle: homepage
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5cf2d429-9442-49de-b0fb-aaaec557b2cd: # TMF
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
