defaultPlacement: end
enableVersioning: true
handle: tables
name: Tables
previewTargets:
  -
    label: Preview
    refresh: '1'
    urlFormat: 'tables/{url}'
propagationMethod: all
siteSettings:
  5cf2d429-9442-49de-b0fb-aaaec557b2cd: # TMF
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
