defaultPlacement: end
enableVersioning: true
handle: tables
name: Tables
previewTargets:
  -
    __assoc__:
      -
        - label
        - Preview
      -
        - urlFormat
        - 'tables/{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5cf2d429-9442-49de-b0fb-aaaec557b2cd:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
