defaultPlacement: end
enableVersioning: true
handle: team
name: Team
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  5cf2d429-9442-49de-b0fb-aaaec557b2cd: # TMF
    enabledByDefault: true
    hasUrls: true
    template: team/_entry
    uriFormat: 'team/{slug}'
type: channel
