cardThumbAlignment: end
cardView:
  - address
tabs:
  -
    elementCondition: null
    elements:
      -
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        dateAdded: null
        disabled: false
        elementCondition: null
        id: null
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        readonly: false
        required: true
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\addresses\LabelField
        uid: 04b93a14-4110-4035-8405-2ae80dce64ff
        userCondition: null
        warning: null
        width: 100
      -
        attribute: countryCode
        dateAdded: null
        elementCondition: null
        id: null
        instructions: null
        label: null
        orientation: null
        requirable: false
        tip: null
        type: craft\fieldlayoutelements\addresses\CountryCodeField
        uid: ed09d100-34da-472d-9f4e-a6e3204e93b3
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: null
        elementCondition: null
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\addresses\AddressField
        uid: 147b1153-df07-4a4e-9f38-4114cf4f9214
        userCondition: null
        warning: null
    name: Content
    uid: 2b9a1ec5-c0e8-48a0-904a-0bb7afaf6e34
    userCondition: null
thumbFieldKey: null
