name: Deploy to digitalocean

on:
  push:
    branches:
      - staging
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Load Environment Variables
      id: load-config
      run: |
        CONFIG_FILE=.github/deploy-config.yml
        if [ "${{ github.ref_name }}" == "staging" ]; then
          ENVIRONMENT="staging"
        elif [ "${{ github.ref_name }}" == "main" ]; then
          ENVIRONMENT="production"
        else
          echo "Unknown branch: ${{ github.ref_name }}"
          exit 1
        fi

        SERVER_IP=$(yq ".environments[\"$ENVIRONMENT\"].server_ip" $CONFIG_FILE)
        SERVER_USER=$(yq ".environments[\"$ENVIRONMENT\"].server_user" $CONFIG_FILE)
        APP_PATH=$(yq ".environments[\"$ENVIRONMENT\"].app_path" $CONFIG_FILE)

        echo "SERVER_IP=${SERVER_IP}" >> $GITHUB_ENV
        echo "SERVER_USER=${SERVER_USER}" >> $GITHUB_ENV
        echo "APP_PATH=${APP_PATH}" >> $GITHUB_ENV
      env:
        YQ_VERSION: "4.34.1"

    - name: Verify Config File
      run: cat .github/deploy-config.yml

    - name: Debug Environment Variables
      run: |
        echo "SERVER_IP=$SERVER_IP"

    - name: Create .ssh Directory
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh

    - name: Add Server to Known Hosts
      run: |
        ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Set up SSH Key
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SERVERPILOT_SSH_KEY }}

    - name: Debug SSH Keys
      run: ssh-add -l

    - name: Deploy to digitalocean
      run: |
        ssh -o StrictHostKeyChecking=no ${{ env.SERVER_USER }}@${{ env.SERVER_IP }} << 'EOF'
          cd ${{ env.APP_PATH }}
          pwd
          rm -rf config/project
          git reset --hard
          git pull origin ${{ github.ref_name }}
          composer install --no-interaction
          php craft up --interactive=0
          php craft project-config/apply
        EOF
      env:
        SERVER_IP: ${{ env.SERVER_IP }}
        SERVER_USER: ${{ env.SERVER_USER }}
        APP_PATH: ${{ env.APP_PATH }}
        SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}